[workspace]
resolver = "2"
members = ["rs/*"]

[workspace.package]
description = "An database for AI Agents built with Object Store."
repository = "https://github.com/ldclabs/anda_db"
homepage = "https://github.com/ldclabs/anda_db"
keywords = ["ai-agent", "object_store", "hnsw", "database"]
categories = [
  "accessibility",
  "web-programming",
  "development-tools",
  "text-processing",
]
edition = "2024"
license = "MIT"

[workspace.dependencies]
ciborium = "0.2"
dashmap = "6.1"
rand = "0.9"
ordered-float = "5.0"
half = { version = "2.5", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
petgraph = "0.7"
thiserror = "1.0"
rayon = "1.10"
num_cpus = "1.16"
parking_lot = "0.12"
chrono = "0.4"
log = "0.4"
uuid = { version = "1.16", features = ["v4"] }
zstd = "0.13.2"
tokio = { version = "1.44", features = ["full"] }
structured-logger = "1"
