[workspace]
resolver = "2"
members = ["rs/*"]

[workspace.package]
description = "An database for AI Agents built with Object Store."
repository = "https://github.com/ldclabs/anda_db"
homepage = "https://github.com/ldclabs/anda_db"
keywords = ["ai-agent", "object_store", "hnsw", "database"]
categories = [
  "accessibility",
  "web-programming",
  "development-tools",
  "text-processing",
]
edition = "2024"
license = "MIT"

[workspace.dependencies]
futures = { version = "0.3" }
tokio = { version = "1.44" }
ciborium = "0.2"
dashmap = "6.1"
rand = "0.9"
rayon = "1.10"
ordered-float = "5.0"
half = { version = "2.5", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
parking_lot = "0.12"
log = "0.4"
tantivy-tokenizer-api = "0.3"
tantivy = "0.22"
tantivy-jieba = "0.11"
structured-logger = "1"
smallvec = "1.14"
criterion = "0.5"
