packages:
  - 'ts/kip-do'
allowBuilds:
  esbuild: true
  sharp: false
  workerd: true
minimumReleaseAgeExclude:
  - '@ldclabs/kip-lang@2.0.2'
  - '@ldclabs/kip-lang@2.1.0'
  - '@ldclabs/kip-lang@2.2.0'
