/**
 * # Executing KML
 *
 * One KML statement is one transaction, whether or not the source wrote
 * `MUTATE { … }` (Spec §5). Execution is the two-phase plan §23 describes:
 *
 * ```text
 * Phase 1   declare every handle
 * Phase 2   interpret every clause, with all handles bound
 * Commit    write once, version once, journal once
 * ```
 *
 * Splitting the phases is what makes forward references legal, and forward
 * references are what make atomic provenance formation possible: an Evidence
 * record generated by an Activity that lists it as an output is a legitimate
 * cycle, and a define-before-use ordering could not express it in one
 * transaction.
 */

import { KipError } from '../errors.js'
import type { AuthContext, EffectiveAuthority } from '../governance/index.js'
import type { JsonMap } from '../json.js'
import type { KmlStatement } from '../kip/ast.js'
import type { SchemaEnvironment } from '../schema/index.js'
import type { Store } from '../store/index.js'
import { Transaction, type Outcome } from '../tx.js'
import { apply, declareHandles, declareConceptType, PLAN_PASSES, planPass } from './clauses.js'
import { mintIngestedEvidence, type IngestContext } from './ingest.js'

/** What one KML execution needs from its caller. */
export interface KmlContext {
  store: Store
  space: string
  env: SchemaEnvironment
  /** `_system.origin` — observed by the runtime, never claimed by content. */
  origin: JsonMap
  /** Request-level parameters. */
  request?: JsonMap
  /**
   * The request envelope's ingestion context (§71.1).
   *
   * Minted into this statement's transaction before the plan runs, so a
   * command can cite `:key` and an abort takes the Evidence with everything
   * else.
   */
  ingest?: IngestContext
  /** Operation-level parameters, which win over request-level ones. */
  operation?: JsonMap
  /** The key that makes a lost response recoverable without writing again. */
  idempotencyKey?: string
  /**
   * What that key was spent on (§33.1, §34.4), so a resend under it can be
   * told apart from a different request reusing it.
   */
  requestDigest?: string
  /** Whether this run may become durable. */
  dryRun?: boolean
  /**
   * What the caller may do here, resolved once for the whole statement.
   *
   * Required, like the read path's: a write that defaulted its authority would
   * be an ungoverned write path arriving by omission.
   */
  authority: EffectiveAuthority
  /** Who the caller is. */
  auth: AuthContext
}

/**
 * Runs one KML statement as a transaction.
 *
 * The caller wraps this in `ctx.storage.transactionSync`, which is what makes a
 * thrown clause roll the whole statement back — shells included.
 */
export function executeKml(
  statement: KmlStatement,
  cx: KmlContext,
): Outcome {
  const tx = new Transaction(
    cx.store,
    cx.space,
    cx.env,
    cx.origin,
    cx.dryRun === true,
    cx.authority,
    cx.auth,
  )

  // §71.1: ingested Evidence is minted before the plan runs, inside this same
  // transaction, so a command can cite it as `:key` and an abort takes it with
  // everything else.
  const ingested = mintIngestedEvidence(tx, cx.ingest, cx.request)
  const request =
    ingested === null ? cx.request : { ...(cx.request ?? {}), ...ingested }

  planKml(tx, statement, request, cx.operation)

  return tx.commit(cx.idempotencyKey ?? '', cx.requestDigest ?? '')
}

/**
 * Runs a statement and returns the outcome or the error, without throwing.
 *
 * A caller that wants the transaction rolled back on failure still has to let
 * the throw escape `transactionSync`, so this is for the paths that have
 * already committed to reporting rather than unwinding.
 */
export function tryExecuteKml(
  statement: KmlStatement,
  cx: KmlContext,
): { ok: Outcome } | { error: KipError } {
  try {
    return { ok: executeKml(statement, cx) }
  } catch (err) {
    return { error: KipError.from(err) }
  }
}

export {
  CORE_STRUCTURAL_FIELDS,
  PLAN_PASSES,
  apply,
  declareHandles,
  declareConceptType,
  planPass,
} from './clauses.js'

export {
  checkIngest,
  mintIngestedEvidence,
  type ElementReference,
  type IngestContext,
  type IngestEvidence,
} from './ingest.js'

export {
  assignments,
  bindings,
  boundValue,
  kipValue,
  mutationValue,
  options,
  parameter,
  referenceId,
  referenceValue,
  scalar,
  scalarNumber,
  scalarText,
  symbolName,
  type Bindings,
} from './value.js'

export {
  Transaction,
  type Outcome,
  type VersionGuard,
  type WriteContext,
} from '../tx.js'

/** Plan bounded host output inside an existing transaction. */
export function planKml(
  tx: Transaction,
  statement: KmlStatement,
  request?: JsonMap,
  operation?: JsonMap,
): void {
  for (const clause of statement.clauses) {
    declareHandles(tx, clause)
  }
  for (const clause of statement.clauses)
    declareConceptType(tx, clause, request, operation)
  // Clause order carries no mutation semantics (§24), so this is a planning
  // order rather than an execution order. See `clauses.planPass`.
  for (let pass = 0; pass < PLAN_PASSES; pass++) {
    if (pass === 3) tx.freezeHandleViews()
    for (const clause of statement.clauses) {
      if (planPass(clause) !== pass) continue
      apply(tx, clause, request, operation)
    }
  }
}
