[package]
name = "anda_kip"
version = "0.2.0"
description = "A Rust implementation of KIP (Knowledge Interaction Protocol)."
keywords = ["KIP", "Knowledge", "Memory", "Anda", "Agent"]
categories = ["database", "data-structures", "text-processing"]
repository = "https://github.com/ldclabs/anda_db/tree/main/rs/anda_kip"
publish = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
nom = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
