[package]
name = "anda_kip"
version = "0.1.0"
description = "A Rust implementation of KIP (Knowledge Interaction Protocol) with Anda DB."
keywords = ["KIP", "Knowledge", "Memory", "Anda", "Agent"]
categories = ["database", "data-structures", "text-processing"]
repository = "https://github.com/ldclabs/anda_db/tree/main/rs/anda_kip"
publish = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
ciborium = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
itertools = { workspace = true }
regex = { workspace = true }
nom = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
