[package]
name = "anda_db_utils"
version = "0.11.0"
description = "A utility Rust library for Anda DB."
keywords = ["anda"]
categories = ["database", "data-structures"]
repository = "https://github.com/ldclabs/anda-db/tree/main/rs/anda_db_utils"
publish = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
cbor2 = { workspace = true }
serde_json = { workspace = true }
