/**
 * Differential corpus — GENERATED FILE, DO NOT EDIT.
 *
 * Regenerate with `pnpm run codegen:oracle-corpus`.
 * Sources: the `rs/anda_kip` and `rs/anda_cognitive_nexus` sources and
 * tests, and fixtures/kip-conformance-2.0.
 */

const CORPUS: readonly string[] = [
  "ARCHIVE \"A-1\"",
  "ARCHIVE \"C-1\"",
  "ARCHIVE :old",
  "ARCHIVE :x",
  "ARCHIVE ?c WHERE { ?c CONCEPT {name:",
  "ARCHIVE ?c WHERE { ?c CONCEPT {name: \"Old note\"} }",
  "ARCHIVE ?c WHERE { ?c CONCEPT {type:",
  "ARCHIVE ?c WHERE { ?c CONCEPT {type: \"Person\"} }",
  "ARCHIVE ?e WHERE { ?e EVIDENCE {} }",
  "ARCHIVE ?m WHERE {\n             ?m CONCEPT {type: \"Experience\"}\n             FILTER(?m.attributes.outcome_status == \"failure\")\n           }",
  "ARCHIVE ?missing WHERE { ?m CONCEPT {type:",
  "ARCHIVE ?missing WHERE { ?m CONCEPT {type: \"Experience\"} }",
  "ARCHIVE ?p WHERE { ?p PROPOSITION (:a, \"related_to\", :b) } LIMIT 1",
  "ASSERT (:a, \"p\", :b) { by: :me }",
  "ASSERT (:a, \"p\", :b) { by: :me, mode: \"stated\" }",
  "ASSERT (:a, \"p\", :b) { by: :me, mode: \"stated\", evidence: [\"E-1\", \"E-2\"] }",
  "ASSERT (:a, \"p\", :b) { by: :me, mode: \"stated\", evidence: [:e1, :e2] }",
  "ASSERT (:a, \"p\", :b) { by: :me, mode: \"stated\", oops: 1 }",
  "ASSERT (:a, \"p\", :b) { mode: \"stated\" }",
  "ASSERT (:alice,",
  "ASSERT (:alice, \"prefers\", :dark_mode) {\n//!         by: :alice,\n//!         mode: \"stated\",\n//!         confidence: 0.9,\n//!         evidence: :msg\n//!     }",
  "ASSERT (:alice, \"prefers\", :dark_mode) { by: :alice, mode: \"stated\" }",
  "ASSERT (desugared)",
  "ASSERT (id: \"P-1\") { by: :me, mode: \"stated\" }",
  "ASSERT ?a (:alice, \"prefers\", :dark_mode) {\n                by: :alice,\n                mode: \"stated\",\n                confidence: 0.9,\n                evidence: :msg\n            }",
  "ASSERT ?a (:alice, \"prefers\", :dark_mode) {\n        by: :alice,\n        mode: \"stated\",\n        confidence: 0.9,\n        evidence: [:msg, :screenshot]\n    } SUPERSEDING :old",
  "ASSERT ?new (:a, \"p\", :b) { by: :me, mode: \"stated\" } SUPERSEDING :old",
  "ASSERT ?new (:alice,",
  "ASSERT ?new (:alice, \"timezone\", \"+09:00\") { by: :alice, mode: \"stated\" }\n//!        SUPERSEDING :old",
  "CHANGES AFTER SEQ",
  "CHANGES AFTER SEQ 42",
  "CHANGES SINCE",
  "CHANGES SINCE :cursor LIMIT 100",
  "CORRECT EVIDENCE",
  "CREATE ACTIVITY",
  "CREATE ASSERTION",
  "CREATE ASSERTION ?a { SET STRUCTURAL { (\"evidence\", ?nowhere) } }",
  "CREATE ASSERTION ?a {{ SET FIELDS {{proposition:",
  "CREATE ASSERTION ?a {{ SET FIELDS {{proposition: \"{proposition}\",\n               asserted_by: {{id: \"C-1\"}}, stance: \"support\", mode: \"stated\", confidence: 0.9}} }}",
  "CREATE ASSERTION ?a {{ SET FIELDS {{proposition: \"{proposition}\",\n           asserted_by: {{id: \"C-1\"}}, stance: \"support\", mode: \"stated\", confidence: 0.9}} }}",
  "CREATE CONCEPT",
  "CREATE CONCEPT ?alice { TYPE",
  "CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" SET ATTRIBUTES {display_name: \"Alice\"} }",
  "CREATE CONCEPT ?b { TYPE",
  "CREATE CONCEPT ?b { TYPE \"Person\" NAME \"Alicia\" }",
  "CREATE CONCEPT ?bob { TYPE \"Person\" NAME \"Bob\" }",
  "CREATE CONCEPT ?c { MATCH {id: \"C-1\"} }",
  "CREATE CONCEPT ?c { TYPE",
  "CREATE CONCEPT ?c { TYPE \"Person\" NAME \"Ali\" }",
  "CREATE CONCEPT ?c { TYPE \"Person\" NAME \"Alice\"\n               SET FIELDS {retention: {expires_at: \"2030-01-01T00:00:00Z\"}} }",
  "CREATE CONCEPT ?c { TYPE \"Person\" NAME \"Alice\"\n               SET FIELDS {retention: {retention_class: \"standard\"}} }",
  "CREATE CONCEPT ?c { TYPE \"Person\" NAME \"Alice\"\n           SET ATTRIBUTES {nickname: \"Al\"} }",
  "CREATE CONCEPT ?c { TYPE \"Person\" NAME \"Alice\"\n           SET FIELDS {governance: {classification: \"public\"}} }",
  "CREATE CONCEPT ?c { TYPE \"Person\" NAME \"Alice\"\n           SET FIELDS {retention: {expires_at: \"2030-01-01T00:00:00Z\"}} }",
  "CREATE CONCEPT ?c { TYPE \"Person\" NAME \"Alice\"\n           SET FIELDS {retention: {legal_hold: true}} }",
  "CREATE CONCEPT ?c { TYPE \"Person\" NAME \"Alice\" }",
  "CREATE CONCEPT ?c { TYPE \"Person\" NAME \"Bob\" SET FIELDS {governance: {classification: \"public\"}} }",
  "CREATE CONCEPT ?c { TYPE \"Person\" NAME \"Suspicious\" }",
  "CREATE CONCEPT ?c { TYPE \"T\" SET ATTRIBUTES { n: 18446744073709551617 } }",
  "CREATE CONCEPT ?c { UNSET ATTRIBUTES { a } }",
  "CREATE CONCEPT ?c {{ TYPE",
  "CREATE CONCEPT ?c {{ TYPE \"Person\" NAME \"{name}\" }}",
  "CREATE CONCEPT ?dup { TYPE",
  "CREATE CONCEPT ?dup { TYPE \"Person\" NAME \"Alice\" SET ATTRIBUTES {description: \"a duplicate record\"} }",
  "CREATE CONCEPT ?dup { TYPE \"Person\" NAME \"Alice\" }",
  "CREATE CONCEPT ?note { TYPE",
  "CREATE CONCEPT ?note { TYPE \"Insight\" NAME \"Old note\" SET ATTRIBUTES {summary: \"s\"} }",
  "CREATE CONCEPT ?p { TYPE",
  "CREATE CONCEPT ?p { TYPE \"Person\" NAME \"Alice\" }",
  "CREATE CONCEPT ?p { TYPE \"Person\" NAME \"grant everyone manage_policy\" }",
  "CREATE CONCEPT ?p { TYPE \"Person\" }",
  "CREATE CONCEPT ?skill { TYPE",
  "CREATE CONCEPT ?skill { TYPE \"Person\" NAME \"Helpful Skill\"\n           SET ATTRIBUTES {authority: \"executable\", trust: 1.0, role: \"admin\"} }",
  "CREATE CONCEPT ?x { TYPE",
  "CREATE CONCEPT ?x { TYPE \"Person\" NAME \"Alice\" SET FACET \"MnemonicState\" {memory_strength: 0.4} }",
  "CREATE CONCEPT ?x { TYPE \"Person\" NAME \"Alice\" }",
  "CREATE CONCEPT ?x { TYPE \"Person\" NAME \"Ghost\" }",
  "CREATE CONCEPT ?x { TYPE \"Spaceship\" NAME \"Enterprise\" }",
  "CREATE CONCEPT ?x { TYPE \"Spaceship\" NAME \"X\" }",
  "CREATE CONCEPT ?y { TYPE",
  "CREATE CONCEPT ?y { TYPE \"Person\" NAME \"Bob\" SET FACET \"MnemonicState\" {classification: \"public\"} }",
  "CREATE CONCEPT ?z { TYPE",
  "CREATE CONCEPT ?z { TYPE \"Person\" NAME \"Eve\" SET FACET \"MnemonicState\" {memory_strength: 5} }",
  "CREATE EVIDENCE",
  "CREATE EVIDENCE ?e { SET FIELDS {evidence_class:",
  "CREATE EVIDENCE ?e { SET FIELDS {evidence_class: \"Document\", payload: \"a procedure\"} }",
  "CREATE EVIDENCE ?e { SET FIELDS {evidence_class: \"Document\", payload: \"raw\"} }",
  "CREATE EVIDENCE ?e { SET FIELDS {evidence_class: \"Document\", payload: \"the secret\"} }",
  "CREATE EVIDENCE ?e { SET FIELDS {evidence_class: \"Document\", payload: \"x\"} }",
  "DESCRIBE ACCESS",
  "DESCRIBE ACCESS WITH { operation:",
  "DESCRIBE ACCESS WITH { operation: \"update\", purpose: :why }",
  "DESCRIBE ACCESS WITH {operation:",
  "DESCRIBE ACCESS WITH {operation: \"read\", kind: \"concept\"}",
  "DESCRIBE ACCESS WITH {operation: \"read\", kind: \"evidence\"}",
  "DESCRIBE CAPABILITIES",
  "DESCRIBE COMPATIBILITY FROM",
  "DESCRIBE COMPATIBILITY TO",
  "DESCRIBE EPISTEMIC POLICY",
  "DESCRIBE EPISTEMIC POLICY \"baseline\"",
  "DESCRIBE ERROR",
  "DESCRIBE ERROR \"NotAnError\"",
  "DESCRIBE ERROR \"VersionConflict\"",
  "DESCRIBE EXECUTION CONTEXT",
  "DESCRIBE FACET",
  "DESCRIBE FACET \"MnemonicState\"",
  "DESCRIBE PACKAGE",
  "DESCRIBE PREDICATE",
  "DESCRIBE PREDICATE \"prefers\"",
  "DESCRIBE PRIMER",
  "DESCRIBE PRIMER DESCRIBE PROTOCOL",
  "DESCRIBE PRIMER MODE",
  "DESCRIBE PRIMER MODE \"compact\"",
  "DESCRIBE PRIMER MODE \"full\"",
  "DESCRIBE PROJECTION CAPABILITY",
  "DESCRIBE PROTOCOL",
  "DESCRIBE SCHEMA ENVIRONMENT AS OF SEQ 42",
  "DESCRIBE SCHEMA ENVIRONMENT AS OF SEQ {created}",
  "DESCRIBE SPACE",
  "DESCRIBE SPACE \"space-1\"",
  "DESCRIBE STRUCTURAL FIELD",
  "DESCRIBE STRUCTURAL FIELD \"has_step\"",
  "DESCRIBE TRANSACTION",
  "DESCRIBE TRANSACTION \"tx-1\"",
  "DESCRIBE TRANSACTION BY IDEMPOTENCY KEY",
  "DESCRIBE TRANSACTION BY IDEMPOTENCY KEY \"formation:1\"",
  "DESCRIBE TRANSACTION BY IDEMPOTENCY KEY \"never-used\"",
  "DESCRIBE TRANSACTION BY IDEMPOTENCY KEY \"write-1\"",
  "DESCRIBE TRUST",
  "DESCRIBE TYPE",
  "DESCRIBE TYPE \"Person\"",
  "DESCRIBE TYPE \"Spaceship\"",
  "DESCRIBE TYPE \"{deep}\"",
  "ENSURE PROPOSITION",
  "ENSURE PROPOSITION (:a, \"related_to\", :b)",
  "ENSURE PROPOSITION (:a, ?p, :b)",
  "ENSURE PROPOSITION (id: \"P-1\")",
  "ENSURE PROPOSITION ?p (:dup,",
  "ENSURE PROPOSITION ?p (:dup, \"prefers\", :dark)",
  "ENSURE PROPOSITION ?p (:subject,",
  "ENSURE PROPOSITION ?p (:subject, \"prefers\", :object)",
  "EXPORT CAPSULE",
  "EXPORT CAPSULE :out WHERE { ?b BELIEF (?p) }",
  "EXPORT CAPSULE :out WHERE { ?c CONCEPT {type:",
  "EXPORT CAPSULE :out WHERE { ?c CONCEPT {type: \"Experience\"} } WITH { redact: true } AS OF SEQ 7",
  "EXPORT CAPSULE :out WHERE { ?c CONCEPT {type: \"T\"} }",
  "EXPORT CAPSULE :out WHERE { ?c {type:",
  "EXPORT CAPSULE :out WHERE { ?c {type: \"T\"} }",
  "EXPORT CAPSULE :out WHERE { }",
  "EXPORT CAPSULE ?a WHERE { ?a ASSERTION {} }",
  "EXPORT CAPSULE ?a WHERE { ?a ASSERTION {} } WITH {closure:",
  "EXPORT CAPSULE ?a WHERE { ?a ASSERTION {} } WITH {closure: \"none\"}",
  "EXPORT CAPSULE ?c WHERE { ?c CONCEPT {name:",
  "EXPORT CAPSULE ?c WHERE { ?c CONCEPT {name: \"Nobody\"} }",
  "EXPORT CAPSULE ?c WHERE { ?c CONCEPT {type:",
  "EXPORT CAPSULE ?c WHERE { ?c CONCEPT {type: \"Person\"} }",
  "EXPORT CAPSULE ?c WHERE { ?c CONCEPT {} }",
  "EXPORT CAPSULE ?e WHERE { ?e EVIDENCE {} }",
  "FIND(\"literal\") WHERE { ?x {a: 1} }",
  "FIND() WHERE { ?x {a: 1} }",
  "FIND(1 + 1) WHERE { ?x {a: 1} }",
  "FIND(?a) WHERE { (?a,",
  "FIND(?a) WHERE { (?a, \"leads_to\"{0,2}, ?b) }",
  "FIND(?a) WHERE { ?a ASSERTION {} }",
  "FIND(?a.confidence)\n           WHERE { ?a ASSERTION {} FILTER(?a.confidence > 0.5) }\n           ORDER BY ?a.confidence",
  "FIND(?a.confidence, ?a.stance) WHERE { ?a ASSERTION {} }",
  "FIND(?a.confidence, ?a.stance, ?a.mode) WHERE { ?a ASSERTION {} }",
  "FIND(?a.evidence_refs)\n           WHERE {\n             ?what CONCEPT {name: \"Dark\"}\n             ?p PROPOSITION (?who, \"prefers\", ?what)\n             ?a ASSERTION {proposition: ?p}\n           }",
  "FIND(?a.governance.authority_lineage) WHERE { ?a ASSERTION {} }",
  "FIND(?a.governance.classification) WHERE { ?a ASSERTION {} }",
  "FIND(?a.lifecycle.status) WHERE { ?a ASSERTION {} }",
  "FIND(?a.lifecycle.status) WHERE { ?a ASSERTION {} } AS OF SEQ 1",
  "FIND(?a.lifecycle.status, ?a.confidence) WHERE { ?a ASSERTION {} } AS OF SEQ 1",
  "FIND(?a.lifecycle.status, ?a.confidence) WHERE {{ ?a ASSERTION {{}} }} AS OF SEQ {claimed}",
  "FIND(?a.name)\n           WHERE {\n             ?a CONCEPT {name: \"A\"}\n             ?d CONCEPT {name: \"D\"}\n             (?a, \"leads_to\"{1,5}, ?d)\n           }",
  "FIND(?a.name)\n           WHERE {\n             ?a CONCEPT {name: \"A\"}\n             ?x CONCEPT {name: \"X\"}\n             (?a, \"leads_to\"{1,5}, ?x)\n           }",
  "FIND(?a.stance)\n           WHERE {\n             ?person CONCEPT {name: \"Alice\"}\n             ?p PROPOSITION (?person, \"prefers\", ?thing)\n             ?a ASSERTION {proposition: ?p}\n           }",
  "FIND(?a.stance)\n           WHERE {\n             ?person CONCEPT {name: \"Alice\"}\n             ?p PROPOSITION (?person, \"prefers\", ?thing)\n             ?a ASSERTION {proposition: ?p}\n           }\n           ORDER BY ?a.stance",
  "FIND(?a.stance)\n           WHERE { ?a ASSERTION {} FILTER(IN(?a.mode, [\"inferred\", \"observed\"])) }",
  "FIND(?a.stance, ?a.confidence)\n           WHERE { ?a ASSERTION {} }\n           ORDER BY ?a.confidence DESC",
  "FIND(?a.valid_time.from) WHERE { ?a ASSERTION {} } FOR TIME",
  "FIND(?a.valid_time.from) WHERE { ?a ASSERTION {} } FOR TIME \"2021-06-01T00:00:00Z\"",
  "FIND(?a.valid_time.from) WHERE { ?a ASSERTION {} } FOR TIME \"2026-06-01T00:00:00Z\"",
  "FIND(?b) WHERE {\n             ?s CONCEPT {name: \"Alice\"}\n             ?o CONCEPT {name: \"Dark\"}\n             ?p PROPOSITION (?s, \"prefers\", ?o)\n             ?b BELIEF (?p)\n           }",
  "FIND(?b) WHERE {\n             ?svc CONCEPT {name: \"api\"}\n             ?v CONCEPT {name: \"healthy\"}\n             ?p PROPOSITION (?svc, \"status\", ?v)\n             ?b BELIEF (?p)\n           }",
  "FIND(?b) WHERE {\n             ?svc CONCEPT {name: \"api\"}\n             ?v CONCEPT {name: \"one\"}\n             ?p PROPOSITION (?svc, \"mentions\", ?v)\n             ?b BELIEF (?p)\n           }",
  "FIND(?b) WHERE {\n  ?s CONCEPT {name: \"Alice\"}\n  ?o CONCEPT {name: \"Quiet\"}\n  ?p PROPOSITION (?s, \"prefers\", ?o)\n  ?b BELIEF (?p)\n} WITH EPISTEMIC {policy: \"strict\"}",
  "FIND(?b) WHERE { ?b BELIEF (:alice,",
  "FIND(?b) WHERE { ?b BELIEF (:alice, \"timezone\", ?tz) }",
  "FIND(?b) WHERE { ?b BELIEF (?nothing) }",
  "FIND(?b) WHERE { ?b BELIEF (?p) }",
  "FIND(?b) WHERE { ?b BELIEF (?s,",
  "FIND(?b) WHERE { ?b BELIEF (?s, \"likes\", ?o) }",
  "FIND(?b) WHERE { UNION { ?b BELIEF (?s,",
  "FIND(?b) WHERE { UNION { ?b BELIEF (?s, \"likes\", ?o) } }",
  "FIND(?b) WHERE {{\n             ?s CONCEPT {{name: \"Alice\"}}\n             ?o CONCEPT {{name: \"Dark\"}}\n             ?p PROPOSITION (?s, \"prefers\", ?o)\n             ?b BELIEF (?p)\n           }}{extra}",
  "FIND(?b, ?slot)\n    WHERE {\n        ?b BELIEF (:alice, \"timezone\", ?tz)\n        ?slot BELIEF SLOT (:alice, \"timezone\")\n        ?a ASSERTION {proposition: (id: \"P-1\"), stance: \"support\"}\n    }\n    AS OF SEQ 4200\n    FOR TIME :world_time\n    WITH EPISTEMIC { explain: \"summary\" }",
  "FIND(?b.policy.id) WHERE {\n  ?s CONCEPT {name: \"Alice\"}\n  ?o CONCEPT {name: \"Quiet\"}\n  ?p PROPOSITION (?s, \"prefers\", ?o)\n  ?b BELIEF (?p)\n}",
  "FIND(?b.status)\n           WHERE {\n             ?person CONCEPT {name: \"Alice\"}\n             ?p PROPOSITION (?person, \"prefers\", ?thing)\n             ?b BELIEF (?p)\n           }",
  "FIND(?b.status) WHERE {\n             ?s CONCEPT {name: \"Alice\"}\n             ?o CONCEPT {name: \"Dark\"}\n             ?p PROPOSITION (?s, \"prefers\", ?o)\n             ?b BELIEF (?p)\n             FILTER(?b.status == \"rejected\")\n           }",
  "FIND(?b.status) WHERE {\n             ?s CONCEPT {name: \"Alice\"}\n             ?o CONCEPT {name: \"Dark\"}\n             ?p PROPOSITION (?s, \"prefers\", ?o)\n             ?b BELIEF (?p)\n             FILTER(?b.support.score > 0.5)\n           }",
  "FIND(?b.status) WHERE {\n  ?s CONCEPT {name: \"Alice\"}\n  ?o CONCEPT {name: \"Quiet\"}\n  ?p PROPOSITION (?s, \"prefers\", ?o)\n  ?b BELIEF (?p)\n}",
  "FIND(?b.status) WHERE { ?p PROPOSITION (?s,",
  "FIND(?b.status) WHERE { ?p PROPOSITION (?s, \"prefers\", ?o) ?b BELIEF (?p) }",
  "FIND(?b.status) WHERE {{ ?p PROPOSITION (?s,",
  "FIND(?b.status) WHERE {{ ?p PROPOSITION (?s, \"prefers\", ?o) ?b BELIEF (?p) }} AS OF SEQ {first}",
  "FIND(?b.support.score, ?b.opposition.score) WHERE {\n  ?s CONCEPT {name: \"Alice\"}\n  ?o CONCEPT {name: \"Quiet\"}\n  ?p PROPOSITION (?s, \"prefers\", ?o)\n  ?b BELIEF (?p)\n}",
  "FIND(?b.support.score_semantics) WHERE {\n  ?s CONCEPT {name: \"Alice\"}\n  ?o CONCEPT {name: \"Quiet\"}\n  ?p PROPOSITION (?s, \"prefers\", ?o)\n  ?b BELIEF (?p)\n}",
  "FIND(?c) WHERE {",
  "FIND(?c) WHERE { ?c CONCEPT {id:",
  "FIND(?c) WHERE { ?c CONCEPT {id: \"C-2\"} }",
  "FIND(?c) WHERE { ?c CONCEPT {id: \"C-99\"} }",
  "FIND(?c) WHERE { ?c CONCEPT {name:",
  "FIND(?c) WHERE { ?c CONCEPT {name: \"Alice\"} }",
  "FIND(?c) WHERE { ?c CONCEPT {name: \"Bob\"} }",
  "FIND(?c) WHERE { ?c CONCEPT {name: \"api\"} }",
  "FIND(?c) WHERE { ?c CONCEPT {type:",
  "FIND(?c) WHERE { ?c CONCEPT {type: \"Person\"} }",
  "FIND(?c) WHERE { ?c CONCEPT {type: \"Person\"} } AS OF SEQ 1",
  "FIND(?c) WHERE { ?c CONCEPT {type: \"Person\"} } AS OF SEQ 3",
  "FIND(?c) WHERE { ?c CONCEPT {} }",
  "FIND(?c) WHERE {{ ?c CONCEPT {{name:",
  "FIND(?c) WHERE {{ ?c CONCEPT {{name: \"{actor}\"}} }}",
  "FIND(?c._system.origin) WHERE { ?c CONCEPT {type:",
  "FIND(?c._system.origin) WHERE { ?c CONCEPT {type: \"Person\"} }",
  "FIND(?c._system.version) WHERE { ?c CONCEPT {name: \"Alice\"} }",
  "FIND(?c.attributes.authority, ?c.governance.max_influence_authority) WHERE { ?c CONCEPT {name: \"Administrator\"} }",
  "FIND(?c.attributes.display_name) WHERE { ?c CONCEPT {name:",
  "FIND(?c.attributes.display_name) WHERE { ?c CONCEPT {name: \"Alice\"} }",
  "FIND(?c.attributes.display_name) WHERE { ?c CONCEPT {name: \"Bob\"} }",
  "FIND(?c.attributes.nickname) WHERE { ?c CONCEPT {type:",
  "FIND(?c.attributes.nickname) WHERE { ?c CONCEPT {type: \"Person\"} }",
  "FIND(?c.governance.classification) WHERE { ?c CONCEPT {key: \"person:alice\"} }",
  "FIND(?c.id) WHERE { ?c CONCEPT {name:",
  "FIND(?c.id) WHERE { ?c CONCEPT {name: \"Alice\"} }",
  "FIND(?c.id, ?c.kind) WHERE { ?c CONCEPT {name: \"Bob\"} }",
  "FIND(?c.id, ?c.name, ?c.governance.purged) WHERE { ?c CONCEPT {state: \"purged\"} }",
  "FIND(?c.name)\n           WHERE {\n             ?c CONCEPT {name: \"Alice\"}\n             UNION { ?c CONCEPT {name: \"Dark mode\"} }\n           }\n           ORDER BY ?c.name",
  "FIND(?c.name)\n           WHERE { ?c CONCEPT {type: \"Person\"} FILTER(CONTAINS(?c.name, \"li\")) }",
  "FIND(?c.name)\n           WHERE { ?c CONCEPT {type: \"Person\"} }\n           ORDER BY ?c.attributes.display_name ASC",
  "FIND(?c.name) WHERE {\n  ?c CONCEPT {name: \"Alice\"}\n  UNION { ?c CONCEPT {name: \"Dark\"} }\n} ORDER BY ?c.name",
  "FIND(?c.name) WHERE {\n  ?c CONCEPT {type: \"Person\"}\n  NOT { ?p PROPOSITION (?c, \"prefers\", ?o) }\n}",
  "FIND(?c.name) WHERE { ?c CONCEPT {type:",
  "FIND(?c.name) WHERE { ?c CONCEPT {type: \"Person\", state: \"archived\"} }",
  "FIND(?c.name) WHERE { ?c CONCEPT {type: \"Person\"}\n           FILTER(?c.attributes.nickname == \"Al\") }",
  "FIND(?c.name) WHERE { ?c CONCEPT {type: \"Person\"} FILTER(?c.name > 5) }",
  "FIND(?c.name) WHERE { ?c CONCEPT {type: \"Person\"} }",
  "FIND(?c.name) WHERE { ?c CONCEPT {type: \"Person\"} } AS OF SEQ 0",
  "FIND(?c.name) WHERE { ?c CONCEPT {type: \"Person\"} } AS OF SEQ 1",
  "FIND(?c.name) WHERE { ?c CONCEPT {type: \"Person\"} } ORDER BY ?c.attributes.display_name ASC",
  "FIND(?c.name) WHERE { ?c CONCEPT {type: \"Person\"} } ORDER BY ?c.name",
  "FIND(?c.name) WHERE { ?c CONCEPT {type: \"Person\"} } ORDER BY ?c.name LIMIT 1",
  "FIND(?c.name) WHERE { ?c CONCEPT {type: \"kip://profiles/cognitive-memory@2.0.0/Person\"} }\n           ORDER BY ?c.name",
  "FIND(?c.name) WHERE { ?c CONCEPT {} }",
  "FIND(?c.name) WHERE { ?c CONCEPT {} } AS OF TIME",
  "FIND(?c.name) WHERE { ?c CONCEPT {} } AS OF TIME \"2000-01-01T00:00:00Z\"",
  "FIND(?c.name) WHERE { ?c CONCEPT {} } AS OF TIME \"2099-01-01T00:00:00Z\"",
  "FIND(?c.name) WHERE { ?c CONCEPT {} } AS OF TX",
  "FIND(?c.name) WHERE { ?c CONCEPT {} } AS OF TX \"kip:space:default#999\"",
  "FIND(?c.name) WHERE {{ ?c CONCEPT {{type:",
  "FIND(?c.name) WHERE {{ ?c CONCEPT {{type: \"Person\"}} }} AS OF SEQ {created}",
  "FIND(?c.name) WHERE {{ ?c CONCEPT {{type: \"Person\"}} }} AS OF SEQ {renamed}",
  "FIND(?c.name) WHERE {{ ?c CONCEPT {{type: \"Person\"}} }} ORDER BY ?c.name LIMIT 1 CURSOR \"{cursor}\"",
  "FIND(?c.name) WHERE {{ ?c CONCEPT {{}} }} AS OF SEQ {renamed}",
  "FIND(?c.name) WHERE {{ ?c CONCEPT {{}} }} AS OF TX",
  "FIND(?c.name) WHERE {{ ?c CONCEPT {{}} }} AS OF TX \"{tx}\"",
  "FIND(?c.name, ?c.attributes.display_name)\n           WHERE {\n             ?c CONCEPT {type: \"Person\"}\n             OPTIONAL { ?c CONCEPT {attributes: ?attrs} }\n           }\n           ORDER BY ?c.name",
  "FIND(?c.name, ?c.attributes.display_name) WHERE { ?c CONCEPT {type:",
  "FIND(?c.name, ?c.attributes.display_name) WHERE { ?c CONCEPT {type: \"Person\"} }",
  "FIND(?c.name, ?c.governance.quarantine_reason)\n           WHERE { ?c CONCEPT {type: \"Person\", state: \"quarantined\"} }",
  "FIND(?c.schema_ref) WHERE { ?c CONCEPT {name: \"Alice\"} }",
  "FIND(?drug.name)\n    WHERE {\n        ?drug {type: \"Drug\"}\n    }",
  "FIND(?drug.name) WHERE { ?drug {type:",
  "FIND(?drug.name) WHERE { ?drug {type: \"Drug\"} }",
  "FIND(?drug.name) WHERE { ?drug {type: \"Drug\"} } LIMIT 10",
  "FIND(?drug.name, COUNT(DISTINCT ?trial))\n            WHERE {\n                ?drug CONCEPT {type: \"Drug\"}\n                (?drug, \"studied_in\", ?trial)\n                FILTER(?drug.attributes.risk_level < 3)\n            }\n            AS OF SEQ 4200\n            FOR TIME \"2026-01-01T00:00:00Z\"\n            WITH EPISTEMIC { explain: \"summary\" }\n            ORDER BY COUNT(?trial) DESC, ?drug.name\n            LIMIT 10\n            CURSOR :page",
  "FIND(?drug_class, COUNT(DISTINCT ?drug))\n    WHERE {\n        ?drug CONCEPT {type: \"Drug\"}\n        (?drug, \"is_class_of\"|\"subclass_of\"{1,3}, ?drug_class)\n        OPTIONAL { ?edge STRUCTURAL (?drug, \"has_step\", ?step) }\n        FILTER(?drug.attributes.risk_level < 3 && !IS_NULL(?drug_class))\n    }\n    ORDER BY COUNT(?drug) DESC\n    LIMIT 10",
  "FIND(?e) WHERE { ?e EVIDENCE {} }",
  "FIND(?e.governance.authority_lineage) WHERE { ?e EVIDENCE {} } ORDER BY ?e.id",
  "FIND(?e.id) WHERE { ?e CONCEPT {state:",
  "FIND(?e.id) WHERE { ?e CONCEPT {state: \"purged\"} }",
  "FIND(?e.id, ?e.governance.classification) WHERE { ?e EVIDENCE {} } ORDER BY ?e.id",
  "FIND(?e.id, ?e.name, ?e.governance.purged) WHERE { ?e CONCEPT {state:",
  "FIND(?e.id, ?e.name, ?e.governance.purged) WHERE { ?e CONCEPT {state: \"purged\"} }",
  "FIND(?e.name) WHERE { ?e CONCEPT {type:",
  "FIND(?e.name) WHERE { ?e CONCEPT {type: \"Experience\"} } AS OF SEQ 1",
  "FIND(?e.name, ?e.governance.purged) WHERE { ?e CONCEPT {state: \"purged\"} }",
  "FIND(?from.name)\n           WHERE { ?to CONCEPT {name: \"D\"} (?from, \"leads_to\"{1,5}, ?to) }\n           ORDER BY ?from.name",
  "FIND(?from.name, ?to.name)\n           WHERE { (?from, \"leads_to\"{2,2}, ?to) }\n           ORDER BY ?from.name, ?to.name",
  "FIND(?m.facets[",
  "FIND(?m.facets[\"MnemonicState\"].salience) WHERE { ?m CONCEPT {name: \"First\"} }",
  "FIND(?m.facets[\"MnemonicState\"].salience, ?m.facets[\"MnemonicState\"].memory_strength)\n           WHERE { ?m CONCEPT {name: \"First\"} }",
  "FIND(?m.name) WHERE { ?m CONCEPT {type:",
  "FIND(?m.name) WHERE { ?m CONCEPT {type: \"Experience\"} }",
  "FIND(?m.name) WHERE { ?m CONCEPT {type: \"Experience\"} } ORDER BY ?m.name",
  "FIND(?m.name, ?m.facets[",
  "FIND(?m.name, ?m.facets[\"MnemonicState\"].memory_strength)\n           WHERE { ?m CONCEPT {type: \"Experience\"} }\n           ORDER BY ?m.name",
  "FIND(?m.name, ?m.facets[\"MnemonicState\"].memory_strength) WHERE { ?m CONCEPT {type: \"Experience\"} } ORDER BY ?m.name",
  "FIND(?m.name, ?m.retention.retention_class)\n           WHERE { ?m CONCEPT {type: \"Experience\"} }\n           ORDER BY ?m.name",
  "FIND(?p)\n           WHERE {\n             ?p PROPOSITION (?s, \"prefers\", ?o)\n             NOT { ?a ASSERTION {proposition: ?p, stance: \"reject\"} }\n           }",
  "FIND(?p) WHERE { ?from CONCEPT {name:",
  "FIND(?p) WHERE { ?from CONCEPT {name: \"A\"} ?p PROPOSITION (?from, \"leads_to\"{1,3}, ?to) }",
  "FIND(?p) WHERE { ?p PROPOSITION (:a, \"related_to\"|\"knows\"{1,3}, :b) }",
  "FIND(?p) WHERE { ?p PROPOSITION (?s,",
  "FIND(?p) WHERE { ?p PROPOSITION (?s, \"prefers\", ?o) }",
  "FIND(?p.confidence) WHERE { ?p PROPOSITION (?s, \"prefers\", ?o) }",
  "FIND(?p.id) WHERE { ?p PROPOSITION (?s,",
  "FIND(?p.id) WHERE { ?p PROPOSITION (?s, \"prefers\", ?o) }",
  "FIND(?p.predicate_ref) WHERE { ?p PROPOSITION (?s, \"prefers\", ?o) }",
  "FIND(?person.name, ?thing.name)\n           WHERE {\n             ?p PROPOSITION (?person, \"prefers\", ?thing)\n           }\n           ORDER BY ?person.name",
  "FIND(?person.name, ?thing.name) WHERE { ?p PROPOSITION (?person, \"prefers\", ?thing) }",
  "FIND(?s.name, ?o.name) WHERE {{ ?p PROPOSITION (?s,",
  "FIND(?s.name, ?o.name) WHERE {{ ?p PROPOSITION (?s, \"prefers\", ?o) }} AS OF SEQ {claimed}",
  "FIND(?slot) WHERE { ?slot BELIEF SLOT (:svc,",
  "FIND(?slot) WHERE { ?slot BELIEF SLOT (:svc, \"status\") }",
  "FIND(?slot) WHERE { ?slot BELIEF SLOT (?anything,",
  "FIND(?slot) WHERE { ?slot BELIEF SLOT (?anything, \"prefers\") }",
  "FIND(?step.name)\n           WHERE {\n             ?exp CONCEPT {name: \"Deploy\"}\n             STRUCTURAL (?exp, \"has_step\", ?step)\n           }\n           ORDER BY ?step.name",
  "FIND(?target.name)\n           WHERE {\n             ?source CONCEPT {name: \"First\"}\n             STRUCTURAL (?source, \"derived_from\", ?target)\n           }",
  "FIND(?target.name)\n           WHERE {\n             ?source CONCEPT {name: \"First\"}\n             STRUCTURAL (?source, \"derived_from\", ?target)\n           }\n           ORDER BY ?target.name",
  "FIND(?thing.name)\n           WHERE {\n             ?person CONCEPT {name: \"Alice\"}\n             ?p PROPOSITION (?person, \"prefers\", ?thing)\n           }",
  "FIND(?to.name)\n           WHERE { ?from CONCEPT {name: \"A\"} (?from, \"leads_to\"{0,1}, ?to) }\n           ORDER BY ?to.name",
  "FIND(?to.name)\n           WHERE { ?from CONCEPT {name: \"A\"} (?from, \"leads_to\"{1,10}, ?to) }\n           ORDER BY ?to.name",
  "FIND(?to.name)\n           WHERE { ?from CONCEPT {name: \"A\"} (?from, \"leads_to\"{1,1}, ?to) }\n           ORDER BY ?to.name",
  "FIND(?to.name)\n           WHERE { ?from CONCEPT {name: \"A\"} (?from, \"leads_to\"{1,2} | \"same_as\", ?to) }\n           ORDER BY ?to.name",
  "FIND(?to.name)\n           WHERE { ?from CONCEPT {name: \"A\"} (?from, \"leads_to\"{1,2}, ?to) }\n           ORDER BY ?to.name",
  "FIND(?to.name)\n           WHERE { ?from CONCEPT {name: \"A\"} (?from, \"leads_to\"{1,}, ?to) }\n           ORDER BY ?to.name",
  "FIND(?to.name)\n           WHERE { ?from CONCEPT {name: \"A\"} (?from, \"leads_to\"{2,3}, ?to) }\n           ORDER BY ?to.name",
  "FIND(?to.name)\n           WHERE { ?from CONCEPT {name: \"A\"} (?from, \"leads_to\"{3}, ?to) }",
  "FIND(?to.name)\n           WHERE { ?from CONCEPT {name: \"A\"} ?p PROPOSITION (?from, \"leads_to\"{1,1}, ?to) }",
  "FIND(?who.name, ?what.name, ?a.confidence, ?a.mode)\n           WHERE {\n             ?what CONCEPT {name: \"Dark\"}\n             ?p PROPOSITION (?who, \"prefers\", ?what)\n             ?a ASSERTION {proposition: ?p, by: ?who}\n           }",
  "FIND(?x)\nWHERE {\n  ?x CONCEPT\n}",
  "FIND(?x)\nWHERE {\n  bad\n}",
  "FIND(?x) WHERE { ?x {a: 1} } trailing",
  "FIND(?x) WHERE { ?x {type:",
  "FIND(?x) WHERE { ?x {type: \"A\"} UNION { ?x {type: \"B\"} } }",
  "FIND(?x) WHERE { ?x {type: \"T\"} }",
  "FIND(?x) WHERE { ?x {type: \"T\"} } AS OF TX :tx FOR TIME :t",
  "FIND(?x) WHERE { ?x {type: \"T\"} } FOR TIME :t",
  "FIND(?x) WHERE {}{}",
  "FIND(AVG(?a.confidence)) WHERE { ?a ASSERTION {} }",
  "FIND(COUNT(?a)) WHERE { ?a ASSERTION {} }",
  "FIND(COUNT(?c)) WHERE {\n  ?c CONCEPT {type: \"Person\"}\n  OPTIONAL { ?p PROPOSITION (?c, \"prefers\", ?o) }\n}",
  "FIND(COUNT(?c)) WHERE { ?c CONCEPT {name: \"Nobody\"} }",
  "FIND(COUNT(?c)) WHERE { ?c CONCEPT {type:",
  "FIND(COUNT(?c)) WHERE { ?c CONCEPT {type: \"Person\", state: \"archived\"} }",
  "FIND(COUNT(?c)) WHERE { ?c CONCEPT {type: \"Person\"} }",
  "FIND(COUNT(?c)) WHERE { ?c CONCEPT {} }",
  "FIND(COUNT(?c)) WHERE { ?c CONCEPT {} } AS OF SEQ 0",
  "FIND(COUNT(?c)) WHERE { ?c CONCEPT {} } AS OF TX \"kip:space:default#9999\"",
  "FIND(COUNT(?c)) WHERE {{ ?c CONCEPT {{}} }} AS OF SEQ {created}",
  "FIND(COUNT(?p)) WHERE { ?p PROPOSITION (?s,",
  "FIND(COUNT(?p)) WHERE { ?p PROPOSITION (?s, \"prefers\", ?o) }",
  "FIND(COUNT(?to)) WHERE { ?from CONCEPT {name:",
  "FIND(COUNT(?to)) WHERE { ?from CONCEPT {name: \"A\"} (?from, \"leads_to\"{1,3}, ?to) }",
  "FIND(COUNT(DISTINCT ?a.stance)) WHERE { ?a ASSERTION {} }",
  "HISTORY ELEMENT",
  "HISTORY ELEMENT \"C-1\" FROM SEQ 1 TO SEQ 9 LIMIT 5",
  "HISTORY ELEMENT \"C-1\" FROM SEQ 1 TO SEQ 99 LIMIT 10",
  "HISTORY SPACE",
  "HISTORY SPACE LIMIT 5",
  "LIST SCHEMA PACKAGES",
  "LIST SCHEMA PACKAGES STATUS",
  "LIST SCHEMA PACKAGES STATUS \"active\" LIMIT 20 CURSOR :page",
  "LIST SCHEMA PACKAGES STATUS \"blocked\"",
  "LIST SCHEMA PACKAGES STATUS :s LIMIT 10 CURSOR :c",
  "LIST TYPES CURSOR :c",
  "LIST TYPES LIMIT 2",
  "MERGE CONCEPT",
  "MERGE CONCEPT :a INTO :b LIMIT 1",
  "MERGE CONCEPT :js INTO :javascript EXPECT VERSION 3",
  "MERGE CONCEPT :s INTO :t",
  "MERGE CONCEPT ?source INTO ?target WHERE { ?source CONCEPT {id: :dup} ?target CONCEPT {id: :alice} }",
  "MERGE CONCEPT ?source INTO ?target WHERE { ?source CONCEPT {id: :s} ?target CONCEPT {id: :t} }",
  "MERGE CONCEPT ?source INTO ?target WHERE { ?source CONCEPT {key: \"person:alice-duplicate\"} ?target CONCEPT {key: \"person:alice\"} }",
  "MERGE CONCEPT ?source INTO ?target WHERE { ?source CONCEPT {key: \"person:alice-duplicate\"} ?target CONCEPT {name: \"Alice\"} }",
  "MUTATE {\n                ASSERT (:a, \"p\", :b) { by: :me, mode: \"stated\" }\n                ASSERT (:c, \"q\", :d) { by: :me, mode: \"stated\" }\n            }",
  "MUTATE {\n                CREATE ASSERTION ?new {\n                    SET FIELDS {proposition: :p, asserted_by: :alice, stance: \"reject\", mode: \"stated\", confidence: 0.8}\n                }\n                SUPERSEDE ASSERTION :old BY ?new\n            }",
  "MUTATE {\n                CREATE CONCEPT ?c { TYPE \"A\" }\n                CREATE CONCEPT ?c { TYPE \"B\" }\n            }",
  "MUTATE {\n                CREATE CONCEPT ?c { TYPE \"Person\" NAME \"Alice\" }\n                ARCHIVE :old\n            }",
  "MUTATE {\n                CREATE CONCEPT ?c { TYPE \"Person\" }\n                CREATE CONCEPT ?c { TYPE \"Drug\" }\n            }",
  "MUTATE {\n                CREATE EVIDENCE ?msg { SET FIELDS { evidence_class: \"user_statement\" } }\n                CREATE ASSERTION ?a {\n                    SET FIELDS { asserted_by: :alice }\n                    SET STRUCTURAL { (\"evidence\", ?msg) {role: \"support\"} }\n                }\n            }",
  "MUTATE {\n            CREATE CONCEPT ?a { TYPE \"Event\" NAME \"A\" SET ATTRIBUTES {summary: \"A\"} }\n            CREATE CONCEPT ?b { TYPE \"Event\" NAME \"B\" SET ATTRIBUTES {summary: \"B\"} }\n            CREATE CONCEPT ?c { TYPE \"Event\" NAME \"C\" SET ATTRIBUTES {summary: \"C\"} }\n            CREATE CONCEPT ?d { TYPE \"Event\" NAME \"D\" SET ATTRIBUTES {summary: \"D\"} }\n            CREATE CONCEPT ?x { TYPE \"Event\" NAME \"X\" SET ATTRIBUTES {summary: \"X\"} }\n            CREATE CONCEPT ?y { TYPE \"Event\" NAME \"Y\" SET ATTRIBUTES {summary: \"Y\"} }\n            ENSURE PROPOSITION ?ab (?a, \"leads_to\", ?b)\n            ENSURE PROPOSITION ?bc (?b, \"leads_to\", ?c)\n            ENSURE PROPOSITION ?cd (?c, \"leads_to\", ?d)\n            ENSURE PROPOSITION ?db (?d, \"leads_to\", ?b)\n            ENSURE PROPOSITION ?xy (?x, \"leads_to\", ?y)\n        }",
  "MUTATE {\n            CREATE CONCEPT ?a { TYPE \"Event\" NAME \"A\" SET ATTRIBUTES {summary: \"A\"} }\n            CREATE CONCEPT ?b { TYPE \"Event\" NAME \"B\" SET ATTRIBUTES {summary: \"B\"} }\n            CREATE CONCEPT ?c { TYPE \"Event\" NAME \"C\" SET ATTRIBUTES {summary: \"C\"} }\n            CREATE CONCEPT ?d { TYPE \"Event\" NAME \"D\" SET ATTRIBUTES {summary: \"D\"} }\n            ENSURE PROPOSITION ?ab (?a, \"leads_to\", ?b)\n            ENSURE PROPOSITION ?bc (?b, \"leads_to\", ?c)\n            ENSURE PROPOSITION ?cd (?c, \"same_as\", ?d)\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice Anderson\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark mode theme\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n            CREATE ASSERTION ?a {\n                SET FIELDS {proposition: ?p, asserted_by: ?alice, stance: \"support\", mode: \"stated\", confidence: 0.9}\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice Local\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" SET ATTRIBUTES {display_name: \"Alice A\"} }\n            CREATE CONCEPT ?bob { TYPE \"Person\" NAME \"Bob\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark mode\" }\n            CREATE CONCEPT ?light { TYPE \"Preference\" NAME \"Light mode\" }\n            ENSURE PROPOSITION ?p1 (?alice, \"prefers\", ?dark)\n            ENSURE PROPOSITION ?p2 (?bob, \"prefers\", ?light)\n            CREATE ASSERTION ?a1 {\n                SET FIELDS {proposition: ?p1, asserted_by: ?alice, stance: \"support\", mode: \"stated\", confidence: 0.9}\n            }\n            CREATE ASSERTION ?a2 {\n                SET FIELDS {proposition: ?p1, asserted_by: ?bob, stance: \"reject\", mode: \"inferred\", confidence: 0.4}\n            }\n            CREATE ASSERTION ?a3 {\n                SET FIELDS {proposition: ?p2, asserted_by: ?bob, stance: \"support\", mode: \"stated\", confidence: 0.6}\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?bob { TYPE \"Person\" NAME \"Bob\" }\n            CREATE CONCEPT ?carol { TYPE \"Person\" NAME \"Carol\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Person\" NAME \"Dark Mode\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n            CREATE ASSERTION ?a {\n                SET FIELDS {proposition: ?p, asserted_by: ?alice,\n                            stance: \"support\", mode: \"stated\", confidence: 0.9}\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Person\" NAME \"Dark Mode\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n            CREATE ASSERTION ?a {\n                SET FIELDS {proposition: ?p, asserted_by: ?alice, stance: \"support\",\n                            mode: \"inferred\", confidence: 0.6}\n                SET STRUCTURAL {(\"evidence\", {id: \"E-1\"}) {role: \"support\"}}\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Person\" NAME \"Dark Mode\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark mode\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n            CREATE ASSERTION ?old {\n                SET FIELDS {proposition: ?p, asserted_by: ?alice, stance: \"support\", mode: \"stated\", confidence: 0.9}\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark mode\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n            CREATE EVIDENCE ?e {\n                SET FIELDS {\n                    evidence_class: \"user_statement\",\n                    payload: \"I prefer dark mode.\",\n                    observed_at: \"2026-08-16T09:00:00Z\"\n                }\n            }\n            CREATE ASSERTION ?a {\n                SET FIELDS {\n                    proposition: ?p,\n                    asserted_by: ?alice,\n                    stance: \"support\",\n                    mode: \"stated\",\n                    confidence: 0.9\n                }\n                SET STRUCTURAL { (\"evidence\", ?e) {role: \"support\"} }\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark mode\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n            CREATE CONCEPT ?light { TYPE \"Preference\" NAME \"Light\" }\n            ENSURE PROPOSITION ?p1 (?alice, \"prefers\", ?dark)\n            ENSURE PROPOSITION ?p2 (?alice, \"prefers\", ?light)\n            CREATE ASSERTION ?a1 {\n                SET FIELDS {proposition: ?p1, asserted_by: ?alice, stance: \"support\", mode: \"stated\"}\n            }\n            CREATE ASSERTION ?a2 {\n                SET FIELDS {proposition: ?p2, asserted_by: ?alice, stance: \"support\", mode: \"stated\"}\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n            CREATE ASSERTION ?a {\n                SET FIELDS {proposition: ?p, asserted_by: ?alice, stance: \"support\", mode: \"stated\", confidence: 0.6}\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n            CREATE ASSERTION ?a {\n                SET FIELDS {proposition: ?p, asserted_by: ?alice, stance: \"support\", mode: \"stated\", confidence: 0.7}\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n            CREATE ASSERTION ?a {\n                SET FIELDS {proposition: ?p, asserted_by: ?alice, stance: \"support\", mode: \"stated\", confidence: 0.9}\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n            CREATE ASSERTION ?old {\n                SET FIELDS {\n                    proposition: ?p, asserted_by: ?alice, stance: \"support\", mode: \"stated\",\n                    valid_time: {from: \"2020-01-01T00:00:00Z\", until: \"2023-01-01T00:00:00Z\"}\n                }\n            }\n            CREATE ASSERTION ?new {\n                SET FIELDS {\n                    proposition: ?p, asserted_by: ?alice, stance: \"support\", mode: \"stated\",\n                    valid_time: {from: \"2023-01-01T00:00:00Z\"}\n                }\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n            CREATE EVIDENCE ?e {\n                SET FIELDS {evidence_class: \"user_statement\", payload: \"I prefer dark mode.\"}\n            }\n            CREATE ASSERTION ?a {\n                SET FIELDS {proposition: ?p, asserted_by: ?alice, stance: \"support\", mode: \"stated\", confidence: 0.9}\n                SET STRUCTURAL { (\"evidence\", ?e) {role: \"support\"} }\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n        }",
  "MUTATE {\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?e1 {\n                TYPE \"Experience\" NAME \"First\"\n                SET ATTRIBUTES {goal: \"learn\", outcome_status: \"success\"}\n                SET FACET \"MnemonicState\" {memory_strength: 0.8, salience: 0.5}\n            }\n            CREATE CONCEPT ?e2 {\n                TYPE \"Experience\" NAME \"Second\"\n                SET ATTRIBUTES {goal: \"learn\", outcome_status: \"failure\"}\n                SET FACET \"MnemonicState\" {memory_strength: 0.4, salience: 0.5}\n            }\n            CREATE CONCEPT ?e3 {\n                TYPE \"Experience\" NAME \"Third\"\n                SET ATTRIBUTES {goal: \"rest\", outcome_status: \"success\"}\n                SET FACET \"MnemonicState\" {memory_strength: 0.2, salience: 0.5}\n            }\n            CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark mode\" }\n            ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n            CREATE EVIDENCE ?ev {\n                SET FIELDS {evidence_class: \"user_statement\", payload: \"I prefer dark mode.\"}\n            }\n            CREATE ASSERTION ?a {\n                SET FIELDS {\n                    proposition: ?p, asserted_by: ?alice, stance: \"support\",\n                    mode: \"stated\", confidence: 0.9\n                }\n                SET STRUCTURAL { (\"evidence\", ?ev) {role: \"support\"} }\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?bob { TYPE \"Person\" NAME \"Bob\" }\n            CREATE ASSERTION ?a2 {\n                SET FIELDS {\n                    proposition: :p, asserted_by: ?bob, stance: \"reject\",\n                    mode: \"stated\", confidence: 0.9\n                }\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?fresh { TYPE \"Experience\" NAME \"Fourth\"\n              SET ATTRIBUTES {goal: \"learn\", outcome_status: \"success\"} }\n            ARCHIVE ?m WHERE { ?m CONCEPT {type: \"Experience\"} }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?m { TYPE \"Experience\" NAME \"Fifth\"\n              SET ATTRIBUTES {goal: \"learn\", outcome_status: \"success\"} }\n            ARCHIVE ?m WHERE { ?m CONCEPT {type: \"Experience\"} }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?other { TYPE \"Person\" NAME \"Someone else\" }\n            CREATE CONCEPT ?light { TYPE \"Preference\" NAME \"Light\" }\n            ENSURE PROPOSITION ?p (?other, \"prefers\", ?light)\n            CREATE EVIDENCE ?e { SET FIELDS {evidence_class: \"observation\", payload: \"unrelated\"} }\n            CREATE ASSERTION ?a {\n                SET FIELDS {proposition: ?p, asserted_by: ?other, stance: \"support\", mode: \"observed\", confidence: 0.5}\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?s1 {\n                TYPE \"ExperienceStep\"\n                NAME \"Step one\"\n                SET ATTRIBUTES {step_kind: \"action\", summary: \"First\"}\n            }\n            CREATE CONCEPT ?s2 {\n                TYPE \"ExperienceStep\"\n                NAME \"Step two\"\n                SET ATTRIBUTES {step_kind: \"action\", summary: \"Second\"}\n            }\n            CREATE CONCEPT ?exp {\n                TYPE \"Experience\"\n                NAME \"Deploy\"\n                SET ATTRIBUTES {goal: \"ship\", outcome_status: \"success\"}\n                SET STRUCTURAL { (\"has_step\", ?s1) (\"has_step\", ?s2) }\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?source { TYPE \"Person\" NAME \"Source X\" }\n            CREATE CONCEPT ?all { TYPE \"Person\" NAME \"Everything\" }\n            ENSURE PROPOSITION ?p (?source, \"prefers\", ?all)\n        }",
  "MUTATE {\n            CREATE CONCEPT ?svc { TYPE \"Service\" NAME \"api\" }\n            CREATE CONCEPT ?a { TYPE \"Status\" NAME \"one\" }\n            CREATE CONCEPT ?b { TYPE \"Status\" NAME \"two\" }\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            ENSURE PROPOSITION ?p1 (?svc, \"mentions\", ?a)\n            ENSURE PROPOSITION ?p2 (?svc, \"mentions\", ?b)\n            CREATE ASSERTION ?a1 {\n                SET FIELDS {proposition: ?p1, asserted_by: ?alice, stance: \"support\", mode: \"stated\", confidence: 0.9}\n            }\n            CREATE ASSERTION ?a2 {\n                SET FIELDS {proposition: ?p2, asserted_by: ?alice, stance: \"support\", mode: \"stated\", confidence: 0.9}\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?svc { TYPE \"Service\" NAME \"api\" }\n            CREATE CONCEPT ?healthy { TYPE \"Status\" NAME \"healthy\" }\n            CREATE CONCEPT ?degraded { TYPE \"Status\" NAME \"degraded\" }\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?bob { TYPE \"Person\" NAME \"Bob\" }\n            ENSURE PROPOSITION ?p1 (?svc, \"status\", ?healthy)\n            ENSURE PROPOSITION ?p2 (?svc, \"status\", ?degraded)\n            CREATE ASSERTION ?a1 {\n                SET FIELDS {proposition: ?p1, asserted_by: ?alice, stance: \"support\", mode: \"observed\", confidence: 0.8}\n            }\n            CREATE ASSERTION ?a2 {\n                SET FIELDS {proposition: ?p2, asserted_by: ?bob, stance: \"support\", mode: \"observed\", confidence: 0.8}\n            }\n        }",
  "MUTATE {\n            CREATE CONCEPT ?svc { TYPE \"Service\" NAME \"api\" }\n            CREATE CONCEPT ?healthy { TYPE \"Status\" NAME \"healthy\" }\n            CREATE CONCEPT ?degraded { TYPE \"Status\" NAME \"degraded\" }\n            CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n            CREATE CONCEPT ?bob { TYPE \"Person\" NAME \"Bob\" }\n            ENSURE PROPOSITION ?p1 (?svc, \"status\", ?healthy)\n            ENSURE PROPOSITION ?p2 (?svc, \"status\", ?degraded)\n            CREATE ASSERTION ?a1 {\n                SET FIELDS {proposition: ?p1, asserted_by: ?alice, stance: \"support\", mode: \"observed\", confidence: 0.9}\n            }\n            CREATE ASSERTION ?a2 {\n                SET FIELDS {proposition: ?p2, asserted_by: ?bob, stance: \"support\", mode: \"observed\", confidence: 0.5}\n            }\n        }",
  "MUTATE {\n            CREATE EVIDENCE ?e {\n                SET FIELDS {evidence_class: \"tool_result\", payload: \"42\"}\n                SET STRUCTURAL { (\"generated_by\", ?act) }\n            }\n            CREATE ACTIVITY ?act {\n                SET FIELDS {activity_class: \"tool_execution\"}\n                SET STRUCTURAL { (\"outputs\", ?e) }\n            }\n        }",
  "MUTATE {\n            CREATE EVIDENCE ?imported { SET FIELDS {evidence_class: \"Document\", payload: \"a skill\"} }\n            CREATE EVIDENCE ?summary { SET FIELDS {evidence_class: \"Document\", payload: \"the gist\"} }\n            CREATE ACTIVITY ?act {\n                SET FIELDS {activity_class: \"Consolidation\", status: \"completed\"}\n                SET STRUCTURAL {(\"inputs\", ?imported) (\"outputs\", ?summary)}\n            }\n        }",
  "MUTATE {\n            CREATE EVIDENCE ?summary { SET FIELDS {evidence_class: \"Document\", payload: \"gist\"} }\n            CREATE ACTIVITY ?act {\n                SET FIELDS {activity_class: \"Consolidation\", status: \"completed\"}\n                SET STRUCTURAL {(\"inputs\", {id: \"E-1\"}) (\"outputs\", ?summary)}\n            }\n        }",
  "MUTATE {\n            CREATE EVIDENCE ?x {SET FIELDS {evidence_class: \"message\", payload: \"a\"}}\n            CREATE ASSERTION ?x {SET FIELDS {proposition: \"P-1\", asserted_by: \"C-1\", stance: \"support\", mode: \"stated\"}}\n        }",
  "MUTATE {\n        CREATE CONCEPT ?alice { TYPE \"Person\" CLIENT KEY \"person:alice\" NAME \"Alice\" }\n        CREATE EVIDENCE ?msg { SET FIELDS { evidence_class: \"user_statement\" } }\n        ENSURE PROPOSITION ?p (?alice, \"prefers\", :dark_mode)\n        CREATE ASSERTION ?claim {\n            SET FIELDS { proposition: ?p, asserted_by: ?alice, stance: \"support\" }\n            SET STRUCTURAL { (\"evidence\", ?msg) {role: \"support\"} }\n        }\n        UPSERT CONCEPT ?drug {\n            MATCH {key: \"drug:aspirin\"}\n            EXPECT VERSION 3\n            SET ATTRIBUTES { risk_level: 2 }\n            UNSET ATTRIBUTES { deprecated_note }\n            SET FACET \"MnemonicState\" { salience: 0.4 }\n        }\n        UPDATE ?c\n            SET FACET \"MnemonicState\" { memory_strength: MUL(?c.facets[\"MnemonicState\"].memory_strength, 0.99) }\n            WHERE { ?c CONCEPT {type: \"Experience\"} }\n            LIMIT 100\n        TRANSITION ACTIVITY :act TO \"succeeded\" SET FIELDS { ended_at: :now }\n        PURGE :leak REFERENCE POLICY \"detach\" CONFIRM \"PURGE\"\n    }",
  "MUTATE {\n  ASSERT ?new (:alice, \"prefers\", :dark) { by: :alice, mode: \"stated\", confidence: 0.4 }\n    SUPERSEDING :old\n}",
  "MUTATE {\n  CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" SET ATTRIBUTES { display_name: \"Alice A\" } }\n  CREATE CONCEPT ?bob { TYPE \"Person\" NAME \"Bob\" }\n  CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n  ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n}",
  "MUTATE {\n  CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" SET FIELDS {key: \"person:alice\"} }\n  CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n  CREATE CONCEPT ?admin { TYPE \"Person\" NAME \"Administrator\" SET ATTRIBUTES {authority: \"executable\", trust: 1.0} }\n  CREATE EVIDENCE ?secret { SET FIELDS {evidence_class: \"Document\", payload: \"an observation\"} }\n  ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n  CREATE ASSERTION ?a {\n    SET FIELDS { proposition: ?p, asserted_by: ?alice, stance: \"support\", mode: \"inferred\", confidence: 0.6 }\n    SET STRUCTURAL { (\"evidence\", ?secret) {role: \"support\"} }\n  }\n}",
  "MUTATE {\n  CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" SET FIELDS {key: \"person:alice\"} }\n  CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n  CREATE CONCEPT ?e1 { TYPE \"Experience\" NAME \"First\" SET ATTRIBUTES {goal: \"learn\", outcome_status: \"success\"} SET FACET \"MnemonicState\" {memory_strength: 0.8, salience: 0.5} }\n  CREATE CONCEPT ?e2 { TYPE \"Experience\" NAME \"Second\" SET ATTRIBUTES {goal: \"learn\", outcome_status: \"failure\"} SET FACET \"MnemonicState\" {memory_strength: 0.4, salience: 0.5} }\n  CREATE CONCEPT ?e3 { TYPE \"Experience\" NAME \"Third\" SET ATTRIBUTES {goal: \"rest\", outcome_status: \"success\"} SET FACET \"MnemonicState\" {memory_strength: 0.2, salience: 0.5} }\n  ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n  CREATE ASSERTION ?a {\n    SET FIELDS { proposition: ?p, asserted_by: ?alice, stance: \"support\", mode: \"stated\", confidence: 0.9 }\n  }\n}",
  "MUTATE {\n  CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n  CREATE CONCEPT ?bob { TYPE \"Person\" NAME \"Bob\" }\n  CREATE CONCEPT ?carol { TYPE \"Person\" NAME \"Carol\" }\n  CREATE CONCEPT ?quiet { TYPE \"Preference\" NAME \"Quiet\" }\n  CREATE CONCEPT ?loud { TYPE \"Preference\" NAME \"Loud\" }\n  ENSURE PROPOSITION ?unspoken (?alice, \"prefers\", ?quiet)\n  ENSURE PROPOSITION ?repeated (?alice, \"prefers\", ?loud)\n}",
  "MUTATE {\n  CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n  CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n  ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n  CREATE ASSERTION ?a {\n    SET FIELDS { proposition: ?p, asserted_by: ?alice, stance: \"support\", mode: \"stated\", confidence: 0.9 }\n  }\n}",
  "MUTATE {\n  CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n  CREATE CONCEPT ?dark { TYPE \"Preference\" NAME \"Dark\" }\n  ENSURE PROPOSITION ?p (?alice, \"prefers\", ?dark)\n  CREATE ASSERTION ?old {\n    SET FIELDS { proposition: ?p, asserted_by: ?alice, stance: \"support\", mode: \"stated\", confidence: 0.9 }\n  }\n}",
  "MUTATE {\n  CREATE CONCEPT ?fresh { TYPE \"Experience\" NAME \"Fourth\" SET ATTRIBUTES {goal: \"learn\", outcome_status: \"success\"} }\n  ARCHIVE ?m WHERE { ?m CONCEPT {type: \"Experience\"} }\n}",
  "MUTATE {\n  CREATE CONCEPT ?svc { TYPE \"Service\" NAME \"api\" }\n  CREATE CONCEPT ?healthy { TYPE \"Status\" NAME \"healthy\" }\n  CREATE CONCEPT ?degraded { TYPE \"Status\" NAME \"degraded\" }\n  ENSURE PROPOSITION ?ok (?svc, \"status\", ?healthy)\n  ENSURE PROPOSITION ?bad (?svc, \"status\", ?degraded)\n}",
  "MUTATE {\n///         CREATE CONCEPT ?alice { TYPE \"Person\" NAME \"Alice\" }\n///         ASSERT (?alice, \"prefers\", :dark_mode) { by: ?alice, mode: \"stated\" }\n///     }",
  "MUTATE { ARCHIVE :old }",
  "MUTATE {{\n             CREATE ASSERTION ?a {{\n               SET FIELDS {{ proposition: :p, asserted_by: :actor, {body} }}\n             }}\n           }}",
  "PREVIEW IMPORT CAPSULE",
  "PREVIEW IMPORT CAPSULE :artifact INTO :space",
  "PREVIEW IMPORT CAPSULE :c INTO",
  "PREVIEW IMPORT CAPSULE :c INTO \"space-1\"",
  "PREVIEW IMPORT CAPSULE :capsule INTO :space",
  "PREVIEW KML \"CREATE CONCEPT ?x { TYPE \\\"Person\\\" NAME \\\"Ghost\\\" }\"",
  "PREVIEW KML \"CREATE CONCEPT ?x { TYPE \\\"Spaceship\\\" NAME \\\"X\\\" }\"",
  "PREVIEW KML :cmd",
  "PREVIEW MERGE :a INTO :b",
  "PURGE \"C-1\" CONFIRM \"PURGE\"",
  "PURGE \"C-1\" REFERENCE POLICY \"authorized_cascade\" CONFIRM \"PURGE\"",
  "PURGE \"E-1\" CONFIRM \"PURGE\"",
  "PURGE \"{alice}\" REFERENCE POLICY \"deny_if_referenced\" CONFIRM \"PURGE\"",
  "PURGE \"{third}\" CONFIRM \"PURGE\"",
  "PURGE :e",
  "PURGE :e CONFIRM \"PURGE\"",
  "PURGE :e CONFIRM \"purge\"",
  "PURGE :x CONFIRM",
  "PURGE :x CONFIRM \"PURGE\"",
  "PURGE ?alice WHERE { ?alice CONCEPT {key: \"person:alice\"} } CONFIRM \"PURGE\"",
  "PURGE ?c WHERE { ?c CONCEPT {name: \"Administrator\"} } CONFIRM \"PURGE\"",
  "PURGE ?c WHERE { ?c CONCEPT {name: \"Administrator\"} } REFERENCE POLICY \"delete_everything\" CONFIRM \"PURGE\"",
  "PURGE ?e WHERE { ?e CONCEPT {name: \"Third\", state: \"archived\"} } CONFIRM \"PURGE\"",
  "RETRACT ASSERTION",
  "RETRACT ASSERTION \"A-1\"",
  "RETRACT ASSERTION :a",
  "RETRACT ASSERTION ?a WHERE { ?a ASSERTION {stance:",
  "RETRACT ASSERTION ?a WHERE { ?a ASSERTION {stance: \"support\"} } LIMIT 10",
  "RETRACT ASSERTION ?a WHERE { ?a ASSERTION {} }",
  "SEARCH ASSERTION",
  "SEARCH ASSERTION \"anything\"",
  "SEARCH COGNITION",
  "SEARCH COGNITION \"dark mode\" WITH TYPE \"Preference\" MODE \"hybrid\" THRESHOLD 0.7 LIMIT 5",
  "SEARCH COGNITION \"dark mode\" WITH TYPE \"Preference\" WITH PREDICATE \"prefers\"\n               MODE \"hybrid\" THRESHOLD 0.7 AS OF SEQ 100 LIMIT 5 CURSOR :c",
  "SEARCH CONCEPT",
  "SEARCH CONCEPT \"Alice\" MODE \"semantic\"",
  "SEARCH CONCEPT \"Anderson\"",
  "SEARCH CONCEPT \"Dark\" WITH TYPE \"Person\"",
  "SEARCH CONCEPT \"Dark\" WITH TYPE \"Preference\"",
  "SEARCH CONCEPT \"Note\"",
  "SEARCH CONCEPT \"aspirin\"",
  "SET RETENTION",
  "SET RETENTION \"{third}\" {{ legal_hold: true }}",
  "SET RETENTION ?m {retention_class:",
  "SET RETENTION ?m {retention_class: \"standard\", expires_at: \"2030-01-01T00:00:00Z\"}\n           WHERE { ?m CONCEPT {type: \"Experience\"} }\n           LIMIT 1",
  "SNAPSHOT",
  "SNAPSHOT AS OF SEQ 9999",
  "SNAPSHOT AS OF SEQ {created}",
  "SNAPSHOT AS OF SEQ {}",
  "SNAPSHOT AS OF TIME",
  "SNAPSHOT AS OF TIME \"2026-01-01T00:00:00Z\"",
  "SUPERSEDE ASSERTION",
  "SUPERSEDE ASSERTION :a1 BY :a2",
  "TOMBSTONE \"C-1\"",
  "TOMBSTONE :x",
  "TRANSITION ACTIVITY",
  "TRANSITION ACTIVITY :act TO \"succeeded\" SET FIELDS { a: 1 } SET FIELDS { b: 2 }",
  "TRANSITION ACTIVITY :act TO \"succeeded\" SET FIELDS { ended_at: :now }",
  "UPDATE \"C-1\" SET FIELDS {governance: {classification: \"public\"}}",
  "UPDATE :a SET FACET",
  "UPDATE :a SET FACET \"MnemonicState\" {salience: 0.3}",
  "UPDATE :a SET FIELDS {name:",
  "UPDATE :a SET FIELDS {name: \"relabelled\"}",
  "UPDATE :a UNSET STRUCTURAL { (",
  "UPDATE :a UNSET STRUCTURAL { (\"evidence\", :ev) }",
  "UPDATE :c SET FIELDS { n: ADD(1, 2) }",
  "UPDATE :c UNSET STRUCTURAL { (\"has_step\", :s) }",
  "UPDATE :c UNSET STRUCTURAL { }",
  "UPDATE :c WHERE { ?c CONCEPT {id: \"C-1\"} }",
  "UPDATE :first SET STRUCTURAL { (",
  "UPDATE :first SET STRUCTURAL { (\"derived_from\", :second) (\"derived_from\", :third) }",
  "UPDATE :first UNSET STRUCTURAL { (",
  "UPDATE :first UNSET STRUCTURAL { (\"derived_from\", :second) }",
  "UPDATE :who\n                          SET FIELDS {name: \"Alice A.\"}\n                          SET ATTRIBUTES {display_name: \"Alice A.\", description: \"renamed\"}",
  "UPDATE :x SET ATTRIBUTES {note:",
  "UPDATE :x SET ATTRIBUTES {note: \"about the tuple\"}",
  "UPDATE :x SET FIELDS {key:",
  "UPDATE :x SET FIELDS {key: \"moved\"}",
  "UPDATE :x SET FIELDS {media_type:",
  "UPDATE :x SET FIELDS {media_type: \"text/plain\"}",
  "UPDATE :x SET FIELDS {retention: {retention_class:",
  "UPDATE :x SET FIELDS {retention: {retention_class: \"standard\"}}",
  "UPDATE ?a SET FIELDS { confidence: 0.1 }\n//!            WHERE { ?a ASSERTION {id: \"A-1\"} }",
  "UPDATE ?a SET FIELDS { confidence: 0.1 } WHERE { ?a ASSERTION {id: \"A-1\"} }",
  "UPDATE ?a SET FIELDS { confidence: 0.1 } WHERE { ?a ASSERTION {} }",
  "UPDATE ?a SET FIELDS { name: \"relabelled\" } WHERE { ?a ASSERTION {} }",
  "UPDATE ?a SET FIELDS { stance: \"reject\" } WHERE { ?a ASSERTION {} }",
  "UPDATE ?a SET STRUCTURAL { (\"evidence\", :e) } WHERE { ?a ASSERTION {id: \"A-1\"} }",
  "UPDATE ?alice SET FIELDS { governance: {classification: \"public\"} } WHERE { ?alice CONCEPT {key: \"person:alice\"} }",
  "UPDATE ?c SET FACET \"MnemonicState\" { memory_strength: MUL(?c.facets[\"MnemonicState\"].memory_strength, 0.99) } WHERE { ?c CONCEPT {id: \"C-1\"} }",
  "UPDATE ?c SET FIELDS { confidence: 0.1 } WHERE { ?c CONCEPT {id: \"C-1\"} }",
  "UPDATE ?c SET FIELDS { n: ADD(?other.n, 1) } WHERE { ?c CONCEPT {id: \"C-1\"} }",
  "UPDATE ?c SET FIELDS {name:",
  "UPDATE ?c SET FIELDS {name: \"Alice A.\"} WHERE { ?c CONCEPT {name: \"Alice\"} }",
  "UPDATE ?c SET STRUCTURAL { (\"has_step\", :s) } WHERE { ?c CONCEPT {id: \"C-1\"} }",
  "UPDATE ?c SET STRUCTURAL { (\"has_step\", ?c) } WHERE { ?c CONCEPT {id: \"C-1\"} }",
  "UPDATE ?e SET FIELDS { payload: \"x\" } WHERE { ?e EVIDENCE {id: \"E-1\"} }",
  "UPDATE ?m\n           SET ATTRIBUTES {goal: \"rest\"}\n           WHERE { ?m CONCEPT {name: \"Third\"} }",
  "UPDATE ?m\n           SET ATTRIBUTES {outcome_status: \"reviewed\"}\n           WHERE {\n             ?m CONCEPT {type: \"Experience\"}\n             FILTER(?m.attributes.goal == \"nothing matches this\")\n           }",
  "UPDATE ?m\n           SET FACET \"MnemonicState\" {\n             memory_strength: MUL(?m.facets[\"MnemonicState\"].memory_strength, 0.5)\n           }\n           WHERE { ?m CONCEPT {type: \"Experience\"} }\n           LIMIT 2",
  "UPDATE ?m SET ATTRIBUTES { outcome_status: \"aborted\" } WHERE { ?m CONCEPT {type: \"Experience\"} FILTER(?m.attributes.goal == \"no such goal\") }",
  "UPDATE ?m SET FACET \"MnemonicState\" { memory_strength: MUL(?m.facets[\"MnemonicState\"].memory_strength, 0.5) } WHERE { ?m CONCEPT {type: \"Experience\"} } LIMIT 2",
  "UPDATE ?p SET FIELDS { subject: :x } WHERE { ?p PROPOSITION (?s, \"q\", ?o) }",
  "UPSERT CONCEPT",
  "UPSERT CONCEPT ?c { MATCH {id: \"C-1\"} }",
  "UPSERT CONCEPT ?c { MATCH {id: :concept_id} }",
  "UPSERT CONCEPT ?c { MATCH {id: ?anything} }",
  "UPSERT CONCEPT ?c { MATCH {key: \"person:alice\"} }",
  "UPSERT CONCEPT ?c { MATCH {name: \"Alice\"} }",
  "UPSERT CONCEPT ?c { SET FIELDS {name: \"Alice\"} }",
  "UPSERT CONCEPT ?dup { MATCH {key: \"person:alice-duplicate\"} SET FIELDS {name: \"Alice\"} }",
  "UPSERT CONCEPT ?m {\n                            MATCH {id: :id}\n                            SET FACET \"MnemonicState\" {salience: 0.9}\n                            UNSET FACET \"MnemonicState\" {memory_strength}\n                            SET STRUCTURAL { (\"derived_from\", :other) }\n                          }",
  "UPSERT CONCEPT ?p {\n             MATCH {key: \"person:alice\"}\n             SET ATTRIBUTES {display_name: \"Alice Smith\"}\n           }",
  "UPSERT CONCEPT ?p {\n             MATCH {key: \"person:alice\"}\n             SET FIELDS {name: \"Alice\"}\n             SET ATTRIBUTES {display_name: \"Alice\"}\n           }",
  "UPSERT CONCEPT ?p { MATCH {key:",
  "UPSERT CONCEPT ?p { MATCH {key: \"k\"} EXPECT VERSION 99 SET FIELDS {name: \"Two\"} }",
  "UPSERT CONCEPT ?p { MATCH {key: \"k\"} SET FIELDS {name: \"One\"} }",
  "VALIDATE IMPORT PLAN :plan",
  "VALIDATE KML :cmd WITH { strict: true }",
  "VALIDATE KQL",
  "VALIDATE KQL \"ARCHIVE \\\"C-1\\\"\"",
  "VALIDATE KQL \"FIND(?c) WHERE { ?c CONCEPT {type: \\\"Person\\\"} }\"",
  "VALIDATE KQL \"FIND(?c) WHERE {\"",
  "VERIFY BLOB \"x\"",
  "VERIFY CAPSULE",
  "VERIFY CAPSULE \"not a capsule\"",
  "VERIFY CAPSULE :artifact",
  "VERIFY RECEIPT \"x\"",
  "VERIFY SCHEMA PACKAGE \"x\"",
  "VERIFY SCHEMA PACKAGE :pkg",
]

export default CORPUS
