[package]
name = "anda_db_shard_proxy"
version = "0.9.0"
description = "A reverse proxy service for Anda DB shard routing"
readme = "README.md"
publish = false
repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum = { workspace = true }
clap = { workspace = true }
dashmap = { workspace = true }
dotenv = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
structured-logger = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
mimalloc = { workspace = true }
hyper-util = { version = "0.1", features = [
  "client-legacy",
  "http1",
  "http2",
  "tokio",
] }
sqlx = { version = "0.9", features = [
  "runtime-tokio",
  "tls-rustls",
  "postgres",
] }

[lib]
doctest = false
