//! # Executing KML
//!
//! One KML statement is one transaction, whether or not the source wrote
//! `MUTATE { ... }` (Spec §5). Execution is the two-phase plan §23 describes:
//!
//! ```text
//! Phase 1   declare every handle
//! Phase 2   interpret every clause, with all handles bound
//! Commit    write once, version once, journal once
//! ```
//!
//! Splitting the phases is what makes forward references legal, and forward
//! references are what make atomic provenance formation possible: an Evidence
//! record generated by an Activity that lists it as an output is a legitimate
//! cycle, and a define-before-use ordering could not express it in one
//! transaction.

pub mod clauses;
pub mod value;

use anda_kip::{
    Json, KipError, KmlStatement, Map, Operation, Request, Response, ResponseContext, Warning,
};

use crate::store::Store;
use crate::store::space::JournalEntry;
use crate::tx::{Outcome, Transaction};

/// Runs one KML statement as a transaction.
pub async fn execute(
    store: &Store,
    space_id: &str,
    statement: &KmlStatement,
    request: &Request,
    operation: &Operation,
) -> Response {
    let dry_run = request.is_dry_run();
    let origin = origin_of(request);

    let mut tx = match Transaction::begin(store, space_id, origin, dry_run).await {
        Ok(tx) => tx,
        Err(err) => return Response::from(err),
    };

    match plan(store, &mut tx, statement, request, operation).await {
        Ok(()) => {}
        Err(err) => {
            // The only durable thing a failed statement wrote is its shells,
            // and they were never visible to any reader.
            tx.abort().await;
            return Response::from(err);
        }
    }

    let entry = JournalEntry {
        idempotency_key: idempotency_key(request, operation),
        ..Default::default()
    };
    let schema_environment_version = tx.env.version;
    match tx.commit(entry).await {
        Ok(outcome) => success(outcome, space_id, schema_environment_version),
        Err(err) => Response::from(err),
    }
}

async fn plan(
    store: &Store,
    tx: &mut Transaction,
    statement: &KmlStatement,
    request: &Request,
    operation: &Operation,
) -> Result<(), KipError> {
    for clause in &statement.clauses {
        clauses::declare_handles(tx, clause).await?;
    }
    // Clause order carries no mutation semantics (§24), so this is a planning
    // order rather than an execution order. See `clauses::plan_pass`.
    for pass in 0..clauses::PLAN_PASSES {
        for clause in &statement.clauses {
            if clauses::plan_pass(clause) != pass {
                continue;
            }
            clauses::apply(
                store,
                tx,
                clause,
                request.parameters.as_ref(),
                operation.parameters.as_ref(),
            )
            .await?;
        }
    }
    Ok(())
}

fn success(outcome: Outcome, space_id: &str, schema_environment_version: u64) -> Response {
    let warnings: Vec<Warning> = outcome
        .warnings
        .iter()
        .map(|message| Warning::Message(message.clone()))
        .collect();
    Response {
        receipt: Some(outcome.receipt.clone()),
        warnings,
        context: Some(ResponseContext {
            space_id: Some(space_id.to_string()),
            schema_environment_version: Some(schema_environment_version),
            compatibility_profile_used: None,
            extensions: None,
        }),
        ..Response::ok(outcome.result())
    }
}

/// The engine's own record of who wrote this, and through what.
///
/// Taken from the transport envelope, never from the command's content: engine
/// origin is what the runtime observed, and content that could set it would be
/// laundering provenance (§26).
fn origin_of(request: &Request) -> Json {
    let mut origin = Map::new();
    if let Some(context) = &request.context
        && let Some(client) = &context.client
    {
        origin.insert("channel".into(), Json::String(client.clone()));
    }
    Json::Object(origin)
}

fn idempotency_key(request: &Request, operation: &Operation) -> String {
    operation
        .idempotency_key
        .clone()
        .or_else(|| {
            request
                .execution
                .as_ref()
                .and_then(|execution| execution.idempotency_key.clone())
        })
        .unwrap_or_default()
}
