//! # Executing KML
//!
//! One KML statement is one transaction, whether or not the source wrote
//! `MUTATE { ... }` (Spec §5). Execution is the two-phase plan §23 describes:
//!
//! ```text
//! Phase 1   declare every handle
//! Phase 2   interpret every clause, with all handles bound
//! Commit    write once, version once, journal once
//! ```
//!
//! Splitting the phases is what makes forward references legal, and forward
//! references are what make atomic provenance formation possible: an Evidence
//! record generated by an Activity that lists it as an output is a legitimate
//! cycle, and a define-before-use ordering could not express it in one
//! transaction.

pub mod clauses;
pub mod select;
pub mod update;
pub mod value;

use anda_kip::{
    ElementKind, ElementReference, Json, KipError, KmlStatement, Map, Operation, OperationResult,
    OperationStatus, Receipt, ReceiptStatus, Request, Response, ResponseContext, ResultContext,
    Warning,
};

use crate::governance::{AuthContext, EffectiveAuthority};
use crate::store::Store;
use crate::store::space::JournalEntry;
use crate::tx::{Outcome, Transaction};

/// Runs one KML statement as a transaction.
pub async fn execute(
    store: &Store,
    space_id: &str,
    statement: &KmlStatement,
    request: &Request,
    operation: &Operation,
    authority: &EffectiveAuthority,
    auth: &AuthContext,
) -> Response {
    let dry_run = request.is_dry_run();
    let origin = origin_of(request, auth);

    let mut tx = match Transaction::begin(
        store,
        space_id,
        origin,
        dry_run,
        authority.clone(),
        auth.clone(),
    )
    .await
    {
        Ok(tx) => tx,
        Err(err) => return Response::from(err),
    };

    // Ingested Evidence is minted before the plan runs, inside this same
    // transaction, so a command can cite it as `:key` and an abort takes it
    // with everything else (§71.1).
    let ingested = match mint_ingested_evidence(store, &mut tx, request, operation).await {
        Ok(bound) => bound,
        Err(err) => {
            tx.abort().await;
            return Response::from(err);
        }
    };
    let parameters = merge_parameters(request.parameters.as_ref(), ingested);

    match plan(store, &mut tx, statement, parameters.as_ref(), operation).await {
        Ok(()) => {}
        Err(err) => {
            // The only durable thing a failed statement wrote is its shells,
            // and they were never visible to any reader.
            tx.abort().await;
            return Response::from(err);
        }
    }

    let key = idempotency_key(request, operation);
    let entry = JournalEntry {
        request_digest: if key.is_empty() {
            String::new()
        } else {
            request_digest(statement, request, operation)
        },
        idempotency_key: scoped_idempotency_key(auth, &key),
        ..Default::default()
    };
    let schema_environment_version = tx.env.version;
    let provenance = access_provenance(statement, authority, auth);
    match tx.commit(entry).await {
        Ok(outcome) => {
            let mut receipt = outcome.receipt.clone();
            if let Some(provenance) = provenance {
                receipt
                    .extensions
                    .get_or_insert_with(Map::new)
                    .insert("governance".to_string(), provenance);
            }
            // The digest covers the members §33.2 names, not the namespaced
            // `extensions`, so it does not matter that the provenance was
            // attached first — and a replay, which cannot rebuild the
            // provenance, recovers the same digest.
            let receipt = crate::tx::seal_receipt(receipt);
            success(outcome, space_id, schema_environment_version, receipt)
        }
        Err(err) => Response::from(err),
    }
}

/// The access-decision provenance a high-impact receipt carries (§33.1).
///
/// Only for high-impact statements. Attaching it to every commit would bury the
/// cases that matter under the ones that do not, and the point of the record is
/// that somebody reads it: an erasure, an export or a Governance change has to
/// be explainable later in terms of the identity and policy that authorized it.
///
/// It names the effective Principal, the delegation chain and the policy
/// version, and deliberately not the Grants of anyone else.
fn access_provenance(
    statement: &KmlStatement,
    authority: &EffectiveAuthority,
    auth: &AuthContext,
) -> Option<Json> {
    let permissions = crate::governance::gate::kml_permissions(statement);
    if !permissions
        .iter()
        .any(|permission| permission.is_always_audited())
    {
        return None;
    }
    Some(serde_json::json!({
        "principal_id": auth.principal_id,
        "delegation_chain": auth.delegation_chain,
        "authentication_strength": auth.auth_strength,
        "purpose": {"value": auth.purpose, "assurance": auth.purpose_assurance},
        "policy": match &authority.policy {
            Some(policy) => serde_json::json!({
                "id": policy.policy_id,
                "version": policy.version,
            }),
            None => Json::Null,
        },
        "operations": permissions
            .iter()
            .map(|permission| permission.as_str())
            .collect::<Vec<_>>(),
    }))
}

/// The request parameters a command sees, with the ingest bindings folded in.
///
/// `None` stays `None` when there is nothing to bind, so the common path
/// allocates nothing.
fn merge_parameters(
    declared: Option<&Map<String, Json>>,
    ingested: Map<String, Json>,
) -> Option<Map<String, Json>> {
    if ingested.is_empty() {
        return declared.cloned();
    }
    let mut merged = declared.cloned().unwrap_or_default();
    merged.extend(ingested);
    Some(merged)
}

async fn plan(
    store: &Store,
    tx: &mut Transaction,
    statement: &KmlStatement,
    parameters: Option<&Map<String, Json>>,
    operation: &Operation,
) -> Result<(), KipError> {
    for clause in &statement.clauses {
        clauses::declare_handles(tx, clause).await?;
    }
    for clause in &statement.clauses {
        clauses::declare_concept_type(tx, clause, parameters, operation.parameters.as_ref())?;
    }
    // Clause order carries no mutation semantics (§24), so this is a planning
    // order rather than an execution order. See `clauses::plan_pass`.
    for pass in 0..clauses::PLAN_PASSES {
        for clause in &statement.clauses {
            if clauses::plan_pass(clause) != pass {
                continue;
            }
            clauses::apply(store, tx, clause, parameters, operation.parameters.as_ref()).await?;
        }
    }
    Ok(())
}

/// Mints the Evidence a request's ingestion context carries (§71.1).
///
/// The point is Evidence fidelity (§88.12, §102.33). A model re-typing an
/// observation inside KML text can truncate, paraphrase or invent it, and the
/// resulting "evidence" is then a fabrication that looks exactly like the real
/// thing. An ingestion context is the runtime's answer: the payload reaches
/// Evidence from the transport envelope, byte for byte, and the command only
/// cites it.
///
/// Three properties this has to keep:
///
/// - **the payload is preserved, not rewritten.** Whatever the envelope
///   carried is what lands in `payload.inline`.
/// - **it is transactional.** The Evidence is staged in the caller's own
///   transaction, so an aborted statement leaves none of it behind.
/// - **each `key` binds as a request parameter.** `evidence: :msg` in the
///   command resolves to the minted Evidence's reference, which is the whole
///   mechanism — the command never spells the content.
///
/// Returns the bindings to merge into the request parameters.
async fn mint_ingested_evidence(
    store: &Store,
    tx: &mut Transaction,
    request: &Request,
    operation: &Operation,
) -> Result<Map<String, Json>, KipError> {
    let Some(ingest) = &request.ingest else {
        return Ok(Map::new());
    };
    ingest.validate()?;

    let mut bound = Map::new();
    let mut ingested_by_key = std::collections::BTreeMap::new();
    for entry in &ingest.evidence {
        // A request parameter of the same name would make it ambiguous which
        // value the command cited, and the two cannot be reconciled: one is a
        // caller-supplied value, the other is an element this request created.
        //
        // Both levels, because §74 merges them into one binding environment:
        // checking only the request's would let an operation-level parameter
        // shadow the ingested reference and leave the Evidence minted, unused
        // and uncited.
        let claimed = |parameters: Option<&Map<String, Json>>| {
            parameters.is_some_and(|parameters| parameters.contains_key(&entry.key))
        };
        if claimed(request.parameters.as_ref()) || claimed(operation.parameters.as_ref()) {
            return Err(KipError::invalid_request_envelope(format!(
                "the ingest key {:?} is also a request parameter; a command citing :{} could \
                 mean either",
                entry.key, entry.key
            )));
        }
        let (payload, artifact_sources) = if let Some(reference) = &entry.payload_artifact {
            if entry.payload.is_some() {
                return Err(KipError::invalid_request_envelope(
                    "ingestion must declare exactly one payload source",
                ));
            }
            if entry
                .media_type
                .as_deref()
                .is_some_and(|v| v != "application/json")
            {
                return Err(KipError::unsupported_capability(
                    "governed artifacts currently carry canonical application/json bytes",
                ));
            }
            store
                .authorized_artifact(&tx.cx.space, reference, &tx.authority, &tx.auth)
                .await?
        } else {
            (
                entry.payload.clone().ok_or_else(|| {
                    KipError::invalid_request_envelope(
                        "ingestion needs payload or payload_artifact",
                    )
                })?,
                Vec::new(),
            )
        };

        let client_key = entry.client_key.clone().unwrap_or_default();

        let mut source_refs = match &entry.source_actor {
            Some(actor) => vec![resolve_source_actor(store, tx, actor).await?],
            None => Vec::new(),
        };
        for source in artifact_sources {
            source_refs.push(serde_json::json!({"id":source}));
        }
        let content_digest = if entry.payload_artifact.is_some() {
            crate::schema::contracts::digest(&payload)?
        } else {
            String::new()
        };
        let observed_at = match &entry.observed_at {
            Some(at) => crate::time::normalize(at, "ingest.observed_at")?,
            None => tx.cx.at.clone(),
        };
        // §71.1: the entry's Facets are validated exactly as `SET FACET` on
        // `CREATE EVIDENCE` would be — which is how instrumentation attaches
        // an OutcomeRecord to an ingested outcome without re-typing anything,
        // and how a member the Facet does not declare fails the whole request.
        let facets = ingested_facets(tx, &entry.facets)?;
        let media_type = entry.media_type.clone().unwrap_or_else(|| {
            if entry.payload_artifact.is_some() {
                "application/json".into()
            } else {
                String::new()
            }
        });
        let existing = match ingested_by_key.get(&client_key).copied() {
            Some(id) => Some(id),
            None => {
                store
                    .find_by_client_key(&tx.cx.space, ElementKind::Evidence, &client_key)
                    .await?
            }
        };
        if let Some(existing) = existing {
            let old = tx.load(existing).await?;
            let crate::store::Element::Evidence(old) = old else {
                return Err(KipError::internal_error(
                    "ingest key resolved to a non-Evidence element",
                ));
            };
            if old.evidence_class != entry.evidence_class
                || old.payload_mode != "inline"
                || anda_kip::canonical_json(&old.payload_inline)
                    != anda_kip::canonical_json(&payload)
                || old.source_refs != source_refs
                || old.media_type != media_type
                || entry.observed_at.is_some() && old.observed_at != observed_at
                || !facets
                    .iter()
                    .all(|(name, value)| old.facets.get(name) == Some(value))
            {
                return Err(KipError::new(
                    anda_kip::KipErrorCode::ClientKeyConflict,
                    "ingest client_key already names a different observation; use a distinct message/ingestion identity",
                ));
            }
            bound.insert(
                entry.key.clone(),
                serde_json::json!({"id": existing.to_string()}),
            );
            continue;
        }

        let id = tx.mint(ElementKind::Evidence).await?;
        let row = crate::store::rows::EvidenceRow {
            _id: id.seq,
            evidence_class: entry.evidence_class.clone(),
            payload_mode: "inline".to_string(),
            payload_inline: payload,
            content_digest,
            media_type,
            observed_at,
            source_keys: source_refs.iter().map(clauses::endpoint_key).collect(),
            source_refs,
            status: "active".to_string(),
            client_key: client_key.clone(),
            facets,
            ..Default::default()
        };
        let element = crate::store::Element::Evidence(Box::new(row));
        tx.authorize_created(&element, crate::governance::Permission::Create)?;
        // §29.8: writing into the consequence channel costs `record_outcome`,
        // whichever path the Evidence arrives by — the envelope is not a way
        // around the gate.
        clauses::require_outcome_authority(tx, &element)?;
        tx.stage_new(id, element, anda_kip::ChangeOp::Create);
        if !client_key.is_empty() {
            ingested_by_key.insert(client_key, id);
        }
        bound.insert(entry.key.clone(), serde_json::json!({"id": id.to_string()}));
    }
    Ok(bound)
}

/// Resolves and validates the Facets an ingest entry attaches (§71.1).
fn ingested_facets(
    tx: &Transaction,
    declared: &std::collections::BTreeMap<String, Map<String, Json>>,
) -> Result<Map<String, Json>, KipError> {
    let mut facets = Map::new();
    for (name, members) in declared {
        let symbol = tx.env.resolve_symbol(
            crate::schema::SymbolKind::Facet,
            name,
            crate::schema::Intent::Write,
        )?;
        facets.insert(symbol.to_string(), Json::Object(members.clone()));
    }
    tx.env
        .validate_facets(
            &facets,
            &crate::schema::EndpointFacts::Element {
                kind: ElementKind::Evidence,
                schema_ref: None,
            },
            crate::schema::Intent::Write,
        )?
        .into_result()?;
    Ok(facets)
}

/// Resolves an ingest entry's `source_actor` to a reference in this Space.
///
/// An element reference — `{id}` or `{type, key}` — and never a name (§71.1,
/// §7.2): the actor is recorded as the Evidence's *source*, and a source slot
/// holding something nothing resolves is a citation a reader cannot follow,
/// indistinguishable later from one that was checked. A key resolves through
/// the Concept Type's lineage (§20.14). The actor is a semantic actor and
/// never a Principal (§88.1), so this looks it up among elements and never in
/// the control plane; one it cannot find is `NotFoundOrNotVisible`.
async fn resolve_source_actor(
    store: &Store,
    tx: &Transaction,
    actor: &ElementReference,
) -> Result<Json, KipError> {
    let missing = |named: String| {
        KipError::not_found_or_not_visible(format!(
            "the ingest source actor {named} names no element in this Space; an Evidence source \
             must resolve to something a reader can follow"
        ))
    };
    if let Some(id) = &actor.id {
        let Ok(parsed) = id.parse::<crate::id::ElementId>() else {
            return Err(missing(format!("{id:?}")));
        };
        return match store.get_element(parsed).await {
            Ok(element) if element.space() == tx.cx.space => {
                Ok(serde_json::json!({"id": parsed.to_string()}))
            }
            _ => Err(missing(format!("{id:?}"))),
        };
    }
    let (Some(type_name), Some(key)) = (&actor.r#type, &actor.key) else {
        return Err(KipError::invalid_request_envelope(
            "ingest source_actor is an element reference: {id} or {type, key}",
        ));
    };
    let symbol = tx.env.resolve_symbol(
        crate::schema::SymbolKind::ConceptType,
        type_name,
        crate::schema::Intent::Read,
    )?;
    match store
        .find_concept_by_key(&tx.cx.space, Some(&symbol.to_string()), key)
        .await?
    {
        Some(row) => Ok(serde_json::json!({
            "id": crate::id::ElementId::new(ElementKind::Concept, row._id).to_string()
        })),
        None => Err(missing(format!("{{type: {type_name:?}, key: {key:?}}}"))),
    }
}

/// The response a recorded transaction produced, handed back on a resend.
///
/// Everything a receipt carries was written at commit, so this reconstructs the
/// original answer rather than approximating it. Two things are honestly
/// different from the first response and say so:
///
/// - a replay warning, because a caller that reads it learns its first attempt
///   landed, which is the fact it resent to find out;
/// - the original run's own warnings are not persisted and are therefore gone.
///   A replay that invented them would be worse than one that says nothing.
///
/// The `origin` is read back from the journal rather than rebuilt: the commit
/// was attributed to whoever made it, and deriving one from the resending
/// caller would attribute the first commit to whoever happened to ask about
/// it. Dropping it instead would change `receipt_digest`, so the Receipt a
/// client recovers would no longer be the one that was sealed (§33.3).
///
/// The governance provenance an audited commit carries in `extensions` is not
/// journalled and is therefore absent here. That is why the digest is sealed
/// over the members §33.2 names and not over `extensions` — otherwise every
/// purge and every tombstone would replay under a digest that did not match
/// the one it committed with.
pub(crate) fn replay(row: &crate::store::rows::TransactionRow) -> Response {
    let committed = row.status == "committed";
    let receipt = crate::tx::seal_receipt(Receipt {
        status: if committed {
            ReceiptStatus::Committed
        } else {
            ReceiptStatus::NoEffect
        },
        tx_id: Some(row.tx_id.clone()),
        space_id: Some(row.space.clone()),
        snapshot_seq: Some(row.snapshot_seq),
        space_seq: committed.then_some(row.seq),
        committed_at: committed.then(|| row.committed_at.clone()),
        transaction_class: Some(row.transaction_class.clone()),
        // Journalled at commit, so the replayed Receipt is the sealed one
        // member for member — which is what a caller comparing the two to
        // learn whether its write landed depends on.
        request_digest: crate::tx::none_if_empty(row.request_digest.clone()),
        semantic_plan_digest: None,
        result_digest: None,
        schema_environment_version: Some(row.schema_environment_version),
        change_summary: Some(crate::tx::summarize(&row.changes)),
        proofs: Vec::new(),
        receipt_digest: None,
        origin: serde_json::from_value(row.origin.clone()).unwrap_or(None),
        extensions: None,
    });
    let mut response = operation_response(
        row.result.clone(),
        &row.space,
        row.schema_environment_version,
        receipt,
    );
    response.warnings = vec![Warning::Message(format!(
        "this is the recorded outcome of transaction {}, replayed under the idempotency key \
         it committed with: nothing ran a second time, and any warnings the first attempt \
         reported are not kept",
        row.tx_id
    ))];
    response
}

fn success(
    outcome: Outcome,
    space_id: &str,
    schema_environment_version: u64,
    receipt: Receipt,
) -> Response {
    let warnings: Vec<Warning> = outcome
        .warnings
        .iter()
        .map(|message| Warning::Message(message.clone()))
        .collect();
    let mut response = operation_response(
        outcome.result(),
        space_id,
        schema_environment_version,
        receipt,
    );
    response.warnings = warnings;
    response
}

/// The single-operation response a state-changing command answers with.
///
/// The Receipt sits on the operation's result (§75, §81): in `sequence` and
/// `independent` execution every state-changing operation returns its own,
/// and the top-level `receipt` is reserved for an `atomic` transaction, which
/// this engine does not run. A transaction that changed nothing reports its
/// operation as `no_effect` (§32.8).
fn operation_response(
    result: Json,
    space_id: &str,
    schema_environment_version: u64,
    receipt: Receipt,
) -> Response {
    let status = if receipt.status == ReceiptStatus::NoEffect {
        OperationStatus::NoEffect
    } else {
        OperationStatus::Succeeded
    };
    Response {
        context: Some(ResponseContext {
            space_id: Some(space_id.to_string()),
            schema_environment_version: Some(schema_environment_version),
            compatibility_profile_used: None,
            extensions: None,
        }),
        results: vec![OperationResult {
            status,
            result: Some(result),
            context: Some(ResultContext {
                space_id: Some(space_id.to_string()),
                snapshot_seq: receipt.snapshot_seq,
                schema_environment_version: Some(schema_environment_version),
                ..Default::default()
            }),
            receipt: Some(receipt),
            ..Default::default()
        }],
        ..Default::default()
    }
}

/// The engine's own record of who wrote this, and through what.
///
/// The Principal comes from the authenticated session and the channel from the
/// transport — never from the command's content. Engine origin is what the
/// runtime observed, and content that could set it would be laundering
/// provenance (§26). No policy can authorize writing it either (§43).
///
/// This is also the field that stays true after a Principal is revoked: what
/// it wrote remains attributable to it (§9).
fn origin_of(request: &Request, auth: &AuthContext) -> Json {
    let mut origin = Map::new();
    if !auth.principal_id.is_empty() {
        origin.insert(
            "principal_id".into(),
            Json::String(auth.principal_id.clone()),
        );
    }
    let channel = if auth.client.is_empty() {
        request
            .context
            .as_ref()
            .and_then(|context| context.client.clone())
    } else {
        Some(auth.client.clone())
    };
    if let Some(channel) = channel {
        origin.insert("channel".into(), Json::String(channel));
    }
    Json::Object(origin)
}

/// The key this request commits under, and the one a resend replays.
///
/// An operation's own key wins over the request's: a batch that shared one key
/// across several writes would have the second replay the first, so the
/// narrower one is the one that means anything.
/// The journal key a client's idempotency key is stored and looked up under.
///
/// §34.2 scopes a key to the Space, the authenticated Principal and the
/// operation class, so that unrelated callers cannot collide: two Principals
/// reusing the same string are two pieces of work, and answering the second
/// with the first's Receipt would hand one caller the other's commit.
pub(crate) fn scoped_idempotency_key(auth: &AuthContext, key: &str) -> String {
    if key.is_empty() {
        String::new()
    } else {
        format!("kml\u{1f}{}\u{1f}{key}", auth.principal_id)
    }
}

/// The retained transaction a client's key names for this caller, if any.
///
/// Journals written before keys were scoped hold the client's key bare; those
/// stay replayable by the Principal that wrote them and by nobody else.
pub(crate) async fn find_transaction_for_key(
    store: &Store,
    space: &str,
    auth: &AuthContext,
    key: &str,
) -> Result<Option<crate::store::rows::TransactionRow>, KipError> {
    if key.is_empty() {
        return Ok(None);
    }
    if let Some(row) = store
        .find_transaction_by_idempotency_key(space, &scoped_idempotency_key(auth, key))
        .await?
    {
        return Ok(Some(row));
    }
    Ok(store
        .find_transaction_by_idempotency_key(space, key)
        .await?
        .filter(|row| {
            row.origin.get("principal_id").and_then(Json::as_str)
                == Some(auth.principal_id.as_str())
        }))
}

pub(crate) fn idempotency_key(request: &Request, operation: &Operation) -> String {
    operation
        .idempotency_key
        .clone()
        .or_else(|| {
            request
                .execution
                .as_ref()
                .and_then(|execution| execution.idempotency_key.clone())
        })
        .unwrap_or_default()
}

/// What the idempotency key was spent on (§33.1, §34.4).
///
/// The digest covers the work the key committed to: the command as written or
/// its pre-parsed AST, and the parameters it would be bound with. §34.3 makes
/// a resend of *the same* request replay; §34.4 makes a resend of a
/// *different* one fail, and without a record of what the first request was
/// there is nothing to tell the two apart — the second write would silently
/// receive the first one's receipt.
///
/// Ingested Evidence is deliberately outside it: a runtime mints those inside
/// the transaction (§71.1), so a replay never re-mints and the recovered
/// Receipt is the first attempt's either way.
pub(crate) fn request_digest(
    statement: &KmlStatement,
    request: &Request,
    operation: &Operation,
) -> String {
    let parameters = match (&request.parameters, &operation.parameters) {
        (None, None) => Json::Null,
        (outer, inner) => {
            let mut merged = outer.clone().unwrap_or_default();
            merged.extend(inner.clone().unwrap_or_default());
            Json::Object(merged)
        }
    };
    // The lowered statement rather than the source text, so that reformatting
    // a resend is still the same request — and so that `ts/kip-do`, which only
    // ever sees the AST, decides the same way.
    crate::tx::digest_of(&serde_json::json!({
        "statement": statement,
        "parameters": parameters,
    }))
}
