//! # Executing KML
//!
//! One KML statement is one transaction, whether or not the source wrote
//! `MUTATE { ... }` (Spec §5). Execution is the two-phase plan §23 describes:
//!
//! ```text
//! Phase 1   declare every handle
//! Phase 2   interpret every clause, with all handles bound
//! Commit    write once, version once, journal once
//! ```
//!
//! Splitting the phases is what makes forward references legal, and forward
//! references are what make atomic provenance formation possible: an Evidence
//! record generated by an Activity that lists it as an output is a legitimate
//! cycle, and a define-before-use ordering could not express it in one
//! transaction.

pub mod clauses;
pub mod select;
pub mod update;
pub mod value;

use anda_kip::{
    ElementKind, Json, KipError, KmlStatement, Map, Operation, Request, Response, ResponseContext,
    Warning,
};

use crate::governance::{AuthContext, EffectiveAuthority};
use crate::store::Store;
use crate::store::space::JournalEntry;
use crate::tx::{Outcome, Transaction};

/// Runs one KML statement as a transaction.
pub async fn execute(
    store: &Store,
    space_id: &str,
    statement: &KmlStatement,
    request: &Request,
    operation: &Operation,
    authority: &EffectiveAuthority,
    auth: &AuthContext,
) -> Response {
    let dry_run = request.is_dry_run();
    let origin = origin_of(request, auth);

    let mut tx = match Transaction::begin(
        store,
        space_id,
        origin,
        dry_run,
        authority.clone(),
        auth.clone(),
    )
    .await
    {
        Ok(tx) => tx,
        Err(err) => return Response::from(err),
    };

    // Ingested Evidence is minted before the plan runs, inside this same
    // transaction, so a command can cite it as `:key` and an abort takes it
    // with everything else (§71.1).
    let ingested = match mint_ingested_evidence(store, &mut tx, request).await {
        Ok(bound) => bound,
        Err(err) => {
            tx.abort().await;
            return Response::from(err);
        }
    };
    let parameters = merge_parameters(request.parameters.as_ref(), ingested);

    match plan(store, &mut tx, statement, parameters.as_ref(), operation).await {
        Ok(()) => {}
        Err(err) => {
            // The only durable thing a failed statement wrote is its shells,
            // and they were never visible to any reader.
            tx.abort().await;
            return Response::from(err);
        }
    }

    let entry = JournalEntry {
        idempotency_key: idempotency_key(request, operation),
        ..Default::default()
    };
    let schema_environment_version = tx.env.version;
    let provenance = access_provenance(statement, authority, auth);
    match tx.commit(entry).await {
        Ok(outcome) => {
            let mut response = success(outcome, space_id, schema_environment_version);
            if let Some(provenance) = provenance
                && let Some(receipt) = response.receipt.as_mut()
            {
                receipt
                    .extensions
                    .get_or_insert_with(Map::new)
                    .insert("governance".to_string(), provenance);
            }
            response
        }
        Err(err) => Response::from(err),
    }
}

/// The access-decision provenance a high-impact receipt carries (§178).
///
/// Only for high-impact statements. Attaching it to every commit would bury the
/// cases that matter under the ones that do not, and the point of the record is
/// that somebody reads it: an erasure, an export or a Governance change has to
/// be explainable later in terms of the identity and policy that authorized it.
///
/// It names the effective Principal, the delegation chain and the policy
/// version, and deliberately not the Grants of anyone else.
fn access_provenance(
    statement: &KmlStatement,
    authority: &EffectiveAuthority,
    auth: &AuthContext,
) -> Option<Json> {
    let permissions = crate::governance::gate::kml_permissions(statement);
    if !permissions
        .iter()
        .any(|permission| permission.is_always_audited())
    {
        return None;
    }
    Some(serde_json::json!({
        "principal_id": auth.principal_id,
        "delegation_chain": auth.delegation_chain,
        "authentication_strength": auth.auth_strength,
        "purpose": {"value": auth.purpose, "assurance": auth.purpose_assurance},
        "policy": match &authority.policy {
            Some(policy) => serde_json::json!({
                "id": policy.policy_id,
                "version": policy.version,
            }),
            None => Json::Null,
        },
        "operations": permissions
            .iter()
            .map(|permission| permission.as_str())
            .collect::<Vec<_>>(),
    }))
}

/// The request parameters a command sees, with the ingest bindings folded in.
///
/// `None` stays `None` when there is nothing to bind, so the common path
/// allocates nothing.
fn merge_parameters(
    declared: Option<&Map<String, Json>>,
    ingested: Map<String, Json>,
) -> Option<Map<String, Json>> {
    if ingested.is_empty() {
        return declared.cloned();
    }
    let mut merged = declared.cloned().unwrap_or_default();
    merged.extend(ingested);
    Some(merged)
}

async fn plan(
    store: &Store,
    tx: &mut Transaction,
    statement: &KmlStatement,
    parameters: Option<&Map<String, Json>>,
    operation: &Operation,
) -> Result<(), KipError> {
    for clause in &statement.clauses {
        clauses::declare_handles(tx, clause).await?;
    }
    // Clause order carries no mutation semantics (§24), so this is a planning
    // order rather than an execution order. See `clauses::plan_pass`.
    for pass in 0..clauses::PLAN_PASSES {
        for clause in &statement.clauses {
            if clauses::plan_pass(clause) != pass {
                continue;
            }
            clauses::apply(store, tx, clause, parameters, operation.parameters.as_ref()).await?;
        }
    }
    Ok(())
}

/// Mints the Evidence a request's ingestion context carries (§71.1).
///
/// The point is Evidence fidelity (§88.12, §102.33). A model re-typing an
/// observation inside KML text can truncate, paraphrase or invent it, and the
/// resulting "evidence" is then a fabrication that looks exactly like the real
/// thing. An ingestion context is the runtime's answer: the payload reaches
/// Evidence from the transport envelope, byte for byte, and the command only
/// cites it.
///
/// Three properties this has to keep:
///
/// - **the payload is preserved, not rewritten.** Whatever the envelope
///   carried is what lands in `payload.inline`.
/// - **it is transactional.** The Evidence is staged in the caller's own
///   transaction, so an aborted statement leaves none of it behind.
/// - **each `key` binds as a request parameter.** `evidence: :msg` in the
///   command resolves to the minted Evidence's reference, which is the whole
///   mechanism — the command never spells the content.
///
/// Returns the bindings to merge into the request parameters.
async fn mint_ingested_evidence(
    store: &Store,
    tx: &mut Transaction,
    request: &Request,
) -> Result<Map<String, Json>, KipError> {
    let Some(ingest) = &request.ingest else {
        return Ok(Map::new());
    };
    ingest.validate()?;

    let mut bound = Map::new();
    for entry in &ingest.evidence {
        // A request parameter of the same name would make it ambiguous which
        // value the command cited, and the two cannot be reconciled: one is a
        // caller-supplied value, the other is an element this request created.
        if request
            .parameters
            .as_ref()
            .is_some_and(|parameters| parameters.contains_key(&entry.key))
        {
            return Err(KipError::invalid_request_envelope(format!(
                "the ingest key {:?} is also a request parameter; a command citing :{} could \
                 mean either",
                entry.key, entry.key
            )));
        }
        // An artifact handle promises bytes this engine has nowhere to fetch
        // from. Minting an Evidence record with an empty payload under a
        // handle that resolves to nothing would be the fabrication the whole
        // mechanism exists to prevent (§85.2).
        if entry.payload_artifact.is_some() {
            return Err(KipError::unsupported_capability(
                "this engine has no artifact store, so `payload_artifact` names bytes it cannot \
                 read; send the observation as an inline `payload`",
            ));
        }
        let payload = entry.payload.clone().ok_or_else(|| {
            KipError::invalid_request_envelope(
                "an ingest entry declares exactly one of `payload` or `payload_artifact`",
            )
        })?;

        // A retry of the same logical ingestion resolves to the Evidence the
        // first attempt minted, exactly as `CLIENT KEY` does on a `CREATE`
        // (§52.1) — which is what makes re-sending a lost request safe.
        let client_key = entry.client_key.clone().unwrap_or_default();
        if let Some(existing) = store
            .find_by_client_key(&tx.cx.space, ElementKind::Evidence, &client_key)
            .await?
        {
            bound.insert(
                entry.key.clone(),
                serde_json::json!({"id": existing.to_string()}),
            );
            continue;
        }

        let source_refs = match &entry.source_actor {
            Some(actor) => vec![resolve_source_actor(store, tx, actor).await?],
            None => Vec::new(),
        };
        let observed_at = match &entry.observed_at {
            Some(at) => crate::time::normalize(at, "ingest.observed_at")?,
            None => tx.cx.at.clone(),
        };

        let id = tx.mint(ElementKind::Evidence).await?;
        let row = crate::store::rows::EvidenceRow {
            _id: id.seq,
            evidence_class: entry.evidence_class.clone(),
            payload_mode: "inline".to_string(),
            payload_inline: payload,
            media_type: entry.media_type.clone().unwrap_or_default(),
            observed_at,
            source_keys: source_refs.iter().map(clauses::endpoint_key).collect(),
            source_refs,
            status: "active".to_string(),
            client_key,
            ..Default::default()
        };
        let element = crate::store::Element::Evidence(Box::new(row));
        tx.authorize_created(&element, crate::governance::Permission::Create)?;
        tx.stage_new(id, element, "create");
        bound.insert(entry.key.clone(), serde_json::json!({"id": id.to_string()}));
    }
    Ok(bound)
}

/// Resolves an ingest entry's `source_actor` to a reference in this Space.
///
/// Refused rather than stored as a bare name. §71.1 records the actor as
/// Evidence *source*, and a source slot holding a string nothing resolves is a
/// citation a reader cannot follow — indistinguishable, later, from one that
/// was checked. The actor is a semantic actor and never a Principal (§88.1),
/// so this looks it up among Concepts and never in the control plane.
async fn resolve_source_actor(
    store: &Store,
    tx: &Transaction,
    actor: &str,
) -> Result<Json, KipError> {
    if let Ok(id) = actor.parse::<crate::id::ElementId>()
        && store.get_element(id).await.is_ok()
    {
        return Ok(serde_json::json!({"id": id.to_string()}));
    }
    if let Some(id) = store
        .find_concept_by_canonical_id(&tx.cx.space, actor)
        .await?
    {
        return Ok(serde_json::json!({"id": id.to_string()}));
    }
    Err(KipError::not_found_or_not_visible(format!(
        "the ingest source actor {actor:?} names no Concept in this Space; an Evidence source \
         must resolve to something a reader can follow"
    )))
}

fn success(outcome: Outcome, space_id: &str, schema_environment_version: u64) -> Response {
    let warnings: Vec<Warning> = outcome
        .warnings
        .iter()
        .map(|message| Warning::Message(message.clone()))
        .collect();
    Response {
        receipt: Some(outcome.receipt.clone()),
        warnings,
        context: Some(ResponseContext {
            space_id: Some(space_id.to_string()),
            schema_environment_version: Some(schema_environment_version),
            compatibility_profile_used: None,
            extensions: None,
        }),
        ..Response::ok(outcome.result())
    }
}

/// The engine's own record of who wrote this, and through what.
///
/// The Principal comes from the authenticated session and the channel from the
/// transport — never from the command's content. Engine origin is what the
/// runtime observed, and content that could set it would be laundering
/// provenance (§26). No policy can authorize writing it either (§43).
///
/// This is also the field that stays true after a Principal is revoked: what
/// it wrote remains attributable to it (§9).
fn origin_of(request: &Request, auth: &AuthContext) -> Json {
    let mut origin = Map::new();
    if !auth.principal_id.is_empty() {
        origin.insert(
            "principal_id".into(),
            Json::String(auth.principal_id.clone()),
        );
    }
    let channel = if auth.client.is_empty() {
        request
            .context
            .as_ref()
            .and_then(|context| context.client.clone())
    } else {
        Some(auth.client.clone())
    };
    if let Some(channel) = channel {
        origin.insert("channel".into(), Json::String(channel));
    }
    Json::Object(origin)
}

fn idempotency_key(request: &Request, operation: &Operation) -> String {
    operation
        .idempotency_key
        .clone()
        .or_else(|| {
            request
                .execution
                .as_ref()
                .and_then(|execution| execution.idempotency_key.clone())
        })
        .unwrap_or_default()
}
